from typing import Any

class Rect:
    x0: float
    y0: float
    x1: float
    y1: float
    width: float
    height: float
    def __init__(self, *args: Any) -> None: ...

class Matrix:
    def __init__(self, x: float = ..., y: float = ...) -> None: ...

class Pixmap:
    def tobytes(self, output: str = ...) -> bytes: ...

class Page:
    rect: Rect
    def get_text(self, option: str = ..., *args: Any, **kwargs: Any) -> Any: ...
    def get_pixmap(self, *args: Any, **kwargs: Any) -> Pixmap: ...
    def get_images(self, *args: Any, **kwargs: Any) -> list[tuple[Any, ...]]: ...

class Document:
    page_count: int
    is_encrypted: bool
    metadata: dict[str, Any]
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Page: ...
    def __enter__(self) -> "Document": ...
    def __exit__(self, *args: Any) -> None: ...
    def load_page(self, page_id: int) -> Page: ...
    def get_toc(self, simple: bool = ...) -> list[list[Any]]: ...
    def extract_image(self, xref: int) -> dict[str, Any]: ...
    def close(self) -> None: ...

def open(filename: str, *args: Any, **kwargs: Any) -> Document: ...
