import { logger } from "../../utils/logger";
import { requestUrl, Notice } from "obsidian";
import { execFile, spawn } from "child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  renameSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "fs";
import { homedir } from "os";
import { join } from "path";
import { buildSandboxPlan } from "../sandboxWrapper";
import { promisify, TextDecoder } from "util";
import { expandPath } from "../../utils/deviceRegistry";
import type { MCPManager } from "../mcpClient";
import {
  buildLocalPdfTools,
  formatAnchorHits,
  isLocalPdfToolName,
  parseLocalPdfToolCall,
  LOCAL_PDF_FETCH_BUDGET,
  LOCAL_PDF_SEARCH_TOP_K,
  type LocalPdfToolContext,
  type LocalPdfToolRunner,
} from "./localPdfTools";
import { buildGuiCliSearchPaths, type CLICredential, type CLIAuthResolver } from "../../auth/cliAuth";
import type {
  LLMProvider,
  PluginSettings,
  LLMMessage,
  LLMContentPart,
  MCPTool,
  StreamChunk,
  ProviderUsage,
} from "../../types";
import type { ToolPolicy } from "../../context/promptRegistry";
import {
  extractAntigravityAnswerFromStderr,
  formatMcpToolResultForDisplay,
  formatQuotaErrorMessage,
  isAntigravityStatusLine,
  isQuotaErrorMessage,
  mapOpenAIFinishReason,
  normalizeOpenAIContent,
  isEphemeralToolPolicy,
  sanitizeOpenAIMessages,
  shouldInjectLocalTools,
  shouldInjectMcpTools,
} from "./messageUtils";

const AGY_READ_PERMISSION = "$read_file$()";
const INCURATOR_AGY_POLICY_HEADER =
  "# Auto-generated by Incurator plugin — do not edit manually.";

/**
 * Prepare Antigravity CLI for non-interactive PDF/image reads without granting
 * blanket tool approval. Antigravity 1.1.3+ soft-denies unapproved tools in
 * headless mode and 1.1.5+ reads persisted permissions from this CLI-specific
 * settings file.
 */
export function syncAgyHeadlessReadPermission(geminiDir: string): void {
  const cliDir = join(geminiDir, "antigravity-cli");
  const settingsPath = join(cliDir, "settings.json");
  mkdirSync(cliDir, { recursive: true });

  let existing: Record<string, unknown> = {};
  if (existsSync(settingsPath)) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(readFileSync(settingsPath, "utf-8"));
    } catch (error) {
      throw new Error(
        `Antigravity CLI settings are malformed; refusing to overwrite ${settingsPath}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error(
        `Antigravity CLI settings must be a JSON object; refusing to overwrite ${settingsPath}.`,
      );
    }
    existing = parsed as Record<string, unknown>;
  }

  const rawPermissions = existing.permissions;
  if (
    rawPermissions !== undefined &&
    (!rawPermissions || typeof rawPermissions !== "object" || Array.isArray(rawPermissions))
  ) {
    throw new Error(
      `Antigravity CLI settings permissions must be an object; refusing to overwrite ${settingsPath}.`,
    );
  }
  const permissions = (rawPermissions ?? {}) as Record<string, unknown>;
  const rawAllow = permissions.allow;
  if (
    rawAllow !== undefined &&
    (!Array.isArray(rawAllow) || rawAllow.some((entry) => typeof entry !== "string"))
  ) {
    throw new Error(
      `Antigravity CLI settings permissions.allow must be a string array; refusing to overwrite ${settingsPath}.`,
    );
  }
  const allow = (rawAllow as string[] | undefined) ?? [];
  const merged = {
    ...existing,
    permissions: {
      ...permissions,
      allow: allow.includes(AGY_READ_PERMISSION)
        ? allow
        : [...allow, AGY_READ_PERMISSION],
    },
  };

  const tempPath = join(
    cliDir,
    `settings.json.incurator-${process.pid}-${Math.random().toString(36).slice(2)}.tmp`,
  );
  try {
    writeFileSync(tempPath, `${JSON.stringify(merged, null, 2)}\n`);
    renameSync(tempPath, settingsPath);
  } finally {
    rmSync(tempPath, { force: true });
  }

  const obsoletePolicyPath = join(geminiDir, "policies", "incurator-read.toml");
  try {
    if (
      existsSync(obsoletePolicyPath) &&
      readFileSync(obsoletePolicyPath, "utf-8").startsWith(INCURATOR_AGY_POLICY_HEADER)
    ) {
      unlinkSync(obsoletePolicyPath);
    }
  } catch (error) {
    logger.warn(
      `Could not clean obsolete Incurator Antigravity policy ${obsoletePolicyPath}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}
export {
  extractAntigravityAnswerFromStderr,
  formatMcpToolResultForDisplay,
  formatQuotaErrorMessage,
  isAntigravityStatusLine,
  isQuotaErrorMessage,
  mapOpenAIFinishReason,
  normalizeOpenAIContent,
  sanitizeOpenAIMessages,
  shouldInjectMcpTools,
} from "./messageUtils";

// ─── Provider-specific request builders ─────────────────────────

interface ProviderAdapter {
  buildUrl(model: string): string;
  buildHeaders(credential: CLICredential): Record<string, string>;
  buildBody(
    messages: LLMMessage[],
    stream: boolean,
    tools?: any[]
  ): Record<string, unknown>;
  parseStreamChunk(raw: string): StreamChunk | null;
  parseFullResponse(json: unknown): string;
}

// ─── Base Adapter (shared SSE envelope + default headers) ────────

/**
 * Common behaviour shared by all provider adapters:
 *  - default Bearer + Content-Type headers (Claude adds anthropic-version)
 *  - SSE envelope parsing (`data: ` prefix, `[DONE]`, JSON.parse + try/catch)
 *
 * Subclasses implement the genuinely provider-specific bits: buildUrl,
 * buildBody, parseFullResponse, and extractDelta (pulling text/done out of a
 * parsed SSE data object).
 */
abstract class BaseProviderAdapter implements ProviderAdapter {
  abstract buildUrl(model: string): string;
  abstract buildBody(
    messages: LLMMessage[],
    stream: boolean,
    tools?: any[]
  ): Record<string, unknown>;
  abstract parseFullResponse(json: unknown): string;

  buildHeaders(credential: CLICredential): Record<string, string> {
    return {
      Authorization: `Bearer ${credential.token}`,
      "Content-Type": "application/json",
    };
  }

  parseStreamChunk(raw: string): StreamChunk | null {
    const line = raw.trim();
    if (!line.startsWith("data: ")) return null;
    const json = line.slice(6);
    if (json === "[DONE]") return { text: "", done: true };
    let parsed: any;
    try {
      parsed = JSON.parse(json);
    } catch {
      return null;
    }
    return this.extractDelta(parsed);
  }

  /** Extract {text, done} from one parsed SSE data object (provider-specific). */
  protected abstract extractDelta(parsed: any): StreamChunk | null;
}

// ─── Antigravity Adapter ────────────────────────────────────────

class AntigravityAdapter extends BaseProviderAdapter {
  buildUrl(model: string): string {
    return `https://generativelanguage.googleapis.com/v1beta/models/${model}:streamGenerateContent?alt=sse`;
  }

  buildBody(messages: LLMMessage[]): Record<string, unknown> {
    const contents = messages
      .filter((m) => m.role !== "system")
      .map((m) => ({
        role: m.role === "assistant" ? "model" : "user",
        parts: this.toParts(m.content),
      }));

    const systemMsg = messages.find((m) => m.role === "system");
    const body: Record<string, unknown> = { contents };
    if (systemMsg) {
      body.systemInstruction = {
        parts: [
          {
            text:
              typeof systemMsg.content === "string"
                ? systemMsg.content
                : systemMsg.content
                    .filter((p) => p.type === "text")
                    .map((p) => (p as { type: "text"; text: string }).text)
                    .join("\n"),
          },
        ],
      };
    }
    return body;
  }

  private toParts(
    content: string | LLMContentPart[]
  ): Array<Record<string, unknown>> {
    if (typeof content === "string") {
      return [{ text: content }];
    }
    return content.map((part) => {
      if (part.type === "text") return { text: part.text };
      return {
        inlineData: { mimeType: part.mimeType, data: part.data },
      };
    });
  }

  protected extractDelta(parsed: any): StreamChunk | null {
    const text = parsed?.candidates?.[0]?.content?.parts?.[0]?.text || "";
    const reason = parsed?.candidates?.[0]?.finishReason as string | undefined;
    // Gemini ends a complete answer with "STOP"; an output-cap cut-off is
    // "MAX_TOKENS" (a recoverable truncation → auto-continue). SAFETY/RECITATION
    // are content-filter blocks that terminate the stream but must NOT be
    // continued. Any non-empty finishReason terminates the stream.
    if (reason === "MAX_TOKENS") {
      return { text, done: true, finishReason: "length", truncated: true };
    }
    if (reason === "SAFETY" || reason === "RECITATION") {
      return { text, done: true, finishReason: "content_filter" };
    }
    return reason ? { text, done: true, finishReason: "stop" } : { text, done: false };
  }

  parseFullResponse(json: unknown): string {
    const data = json as {
      candidates?: Array<{
        content?: { parts?: Array<{ text?: string }> };
      }>;
    };
    return data?.candidates?.[0]?.content?.parts?.[0]?.text || "";
  }
}

// ─── Claude Adapter ─────────────────────────────────────────────

class ClaudeAdapter extends BaseProviderAdapter {
  buildUrl(): string {
    return "https://api.anthropic.com/v1/messages";
  }

  buildHeaders(credential: CLICredential): Record<string, string> {
    return {
      Authorization: `Bearer ${credential.token}`,
      "anthropic-version": "2023-06-01",
      "Content-Type": "application/json",
    };
  }

  buildBody(
    messages: LLMMessage[],
    stream: boolean,
    tools?: any[]
  ): Record<string, unknown> {
    const systemMsg = messages.find((m) => m.role === "system");
    const chatMessages = messages
      .filter((m) => m.role !== "system")
      .map((m) => ({
        role: m.role,
        content: this.toContent(m.content),
      }));

    return {
      model: "", // Will be overridden
      max_tokens: 8192,
      stream,
      ...(systemMsg
        ? {
            system:
              typeof systemMsg.content === "string"
                ? systemMsg.content
                : systemMsg.content
                    .filter((p) => p.type === "text")
                    .map(
                      (p) => (p as { type: "text"; text: string }).text
                    )
                    .join("\n"),
          }
        : {}),
      messages: chatMessages,
    };
  }

  private toContent(
    content: string | LLMContentPart[]
  ): string | Array<Record<string, unknown>> {
    if (typeof content === "string") return content;
    return content.map((part) => {
      if (part.type === "text") return { type: "text", text: part.text };
      return {
        type: "image",
        source: {
          type: "base64",
          media_type: part.mimeType,
          data: part.data,
        },
      };
    });
  }

  protected extractDelta(parsed: any): StreamChunk | null {
    if (parsed.type === "content_block_delta") {
      return { text: parsed.delta?.text || "", done: false };
    }
    // Claude reports the terminal reason on `message_delta` (stop_reason:
    // "end_turn" | "max_tokens" | "tool_use" | ...) just before `message_stop`.
    // Surface a truncation flag here so the chat layer can auto-continue.
    if (parsed.type === "message_delta" && parsed.delta?.stop_reason === "max_tokens") {
      return { text: "", done: false, finishReason: "length", truncated: true };
    }
    if (parsed.type === "message_stop") {
      return { text: "", done: true };
    }
    return null;
  }

  parseFullResponse(json: unknown): string {
    const data = json as {
      content?: Array<{ type: string; text?: string }>;
    };
    return (
      data?.content
        ?.filter((b) => b.type === "text")
        .map((b) => b.text || "")
        .join("") || ""
    );
  }
}

// ─── OpenAI Adapter ─────────────────────────────────────────────

class OpenAIAdapter extends BaseProviderAdapter {
  buildUrl(): string {
    return "https://api.openai.com/v1/chat/completions";
  }

  buildBody(
    messages: LLMMessage[],
    stream: boolean,
    tools?: any[]
  ): Record<string, unknown> {
    const body: Record<string, unknown> = {
      model: "", // Will be overridden
      stream,
      messages: sanitizeOpenAIMessages(messages).map((m) => {
        const mapped: any = {
          role: m.role,
          content: normalizeOpenAIContent(m, (c) => this.toContent(c)),
        };
        if (m.name) mapped.name = m.name;
        if (m.tool_calls) mapped.tool_calls = m.tool_calls;
        if (m.tool_call_id) mapped.tool_call_id = m.tool_call_id;
        return mapped;
      }),
    };
    if (tools && tools.length > 0) {
      body.tools = tools;
    }
    return body;
  }

  private toContent(
    content: string | LLMContentPart[]
  ): string | Array<Record<string, unknown>> {
    if (typeof content === "string") return content;
    return content.map((part) => {
      if (part.type === "text") return { type: "text", text: part.text };
      return {
        type: "image_url",
        image_url: {
          url: `data:${part.mimeType};base64,${part.data}`,
        },
      };
    });
  }

  protected extractDelta(parsed: any): StreamChunk | null {
    const delta = parsed.choices?.[0]?.delta;
    return {
      text: delta?.content || "",
      reasoning_content: delta?.reasoning_content,
      tool_calls: delta?.tool_calls,
      ...mapOpenAIFinishReason(parsed.choices?.[0]?.finish_reason),
    };
  }

  parseFullResponse(json: unknown): string {
    const data = json as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    return data?.choices?.[0]?.message?.content || "";
  }
}

class DeepSeekAdapter extends OpenAIAdapter {
  buildUrl(): string {
    return "https://api.deepseek.com/chat/completions";
  }
}

// ─── Ollama Adapter (OpenAI-compatible /v1/chat/completions) ────

class OllamaAdapter extends BaseProviderAdapter {
  constructor(private host: string) {
    super();
  }

  buildUrl(): string {
    return `${this.host.replace(/\/$/, "")}/v1/chat/completions`;
  }

  buildHeaders(): Record<string, string> {
    return { "Content-Type": "application/json" };
  }

  buildBody(messages: LLMMessage[], stream: boolean, tools?: any[]): Record<string, unknown> {
    const body: Record<string, unknown> = {
      model: "", // overridden by caller
      stream,
      messages: sanitizeOpenAIMessages(messages).map((m) => {
        const mapped: any = {
          role: m.role,
          content: normalizeOpenAIContent(m, (c) => this.toContent(c)),
        };
        if (m.name) mapped.name = m.name;
        if (m.tool_calls) mapped.tool_calls = m.tool_calls;
        if (m.tool_call_id) mapped.tool_call_id = m.tool_call_id;
        return mapped;
      }),
    };
    if (tools && tools.length > 0) {
      body.tools = tools;
    }
    return body;
  }

  private toContent(content: string | LLMContentPart[]): string | Array<Record<string, unknown>> {
    if (typeof content === "string") return content;
    return content.map((part) => {
      if (part.type === "text") return { type: "text", text: part.text };
      return { type: "image_url", image_url: { url: `data:${part.mimeType};base64,${part.data}` } };
    });
  }

  protected extractDelta(parsed: any): StreamChunk | null {
    const delta = parsed.choices?.[0]?.delta;
    return {
      text: delta?.content || "",
      reasoning_content: delta?.reasoning_content,
      tool_calls: delta?.tool_calls,
      ...mapOpenAIFinishReason(parsed.choices?.[0]?.finish_reason),
    };
  }

  parseFullResponse(json: unknown): string {
    const data = json as { choices?: Array<{ message?: { content?: string } }> };
    return data?.choices?.[0]?.message?.content || "";
  }
}

// ─── Main LLM Client ────────────────────────────────────────────

export const ADAPTERS: Record<LLMProvider, ProviderAdapter> = {
  antigravity: new AntigravityAdapter(),
  claude: new ClaudeAdapter(),
  openai: new OpenAIAdapter(),
  ollama: new OllamaAdapter("http://localhost:11434"), // host updated at runtime
  deepseek: new DeepSeekAdapter(),
};

const execFileAsync = promisify(execFile);
const CLI_TIMEOUT_MS = 5 * 60 * 1000;

function isAbortError(error: unknown): boolean {
  return typeof error === "object" && error !== null &&
    "name" in error && error.name === "AbortError";
}

interface ExposedMcpTool {
  type: "function";
  function: {
    name: string;
    description?: string;
    parameters: MCPTool["inputSchema"];
  };
}

interface McpToolRoute {
  serverName: string;
  toolName: string;
}

/** Build a bijective model-facing tool list without reverse-parsing sanitized names. */
export function buildMcpToolExposure(
  rawTools: Array<MCPTool & { serverName: string }>,
): { tools: ExposedMcpTool[]; routes: Map<string, McpToolRoute> } {
  const routes = new Map<string, McpToolRoute>();
  const tools = rawTools.map((tool) => {
    const sanitized = `${tool.serverName}__${tool.name}`
      .replace(/[^a-zA-Z0-9_-]/g, "_") || "mcp_tool";
    let exposedName = sanitized;
    let suffix = 2;
    while (routes.has(exposedName)) {
      exposedName = `${sanitized}__${suffix}`;
      suffix += 1;
    }
    routes.set(exposedName, { serverName: tool.serverName, toolName: tool.name });
    return {
      type: "function" as const,
      function: {
        name: exposedName,
        description: tool.description,
        parameters: tool.inputSchema,
      },
    };
  });
  return { tools, routes };
}

export class LLMClient {
  private getAugmentedEnv(extraEnv?: Record<string, string | undefined>): NodeJS.ProcessEnv {
    const home = process.env.HOME || process.env.USERPROFILE || "";
    const customPaths = buildGuiCliSearchPaths(home).join(":");

    const currentPath = process.env.PATH || "";
    const newPath = currentPath ? `${customPaths}:${currentPath}` : customPaths;
    let tempEnv: Record<string, string> = {};
    try {
      const tempDir = this.cliTempDir();
      tempEnv = { TMPDIR: tempDir, TEMP: tempDir, TMP: tempDir };
    } catch {
      tempEnv = {};
    }

    return {
      ...process.env,
      ...extraEnv,
      ...tempEnv,
      PATH: newPath,
    };
  }
  private settings: PluginSettings;
  private auth: CLIAuthResolver;
  private foregroundRequestControllers = new Set<AbortController>();
  private foregroundRequestController: AbortController | null = null;
  private requestAbortCleanup = new WeakMap<AbortController, () => void>();
  // v0.28.0 interactive chat image channel: per-CLI-call temp PNG dir + paths.
  // Set by messagesToCliPrompt → contentToCliText, read by buildCliCommand to
  // scope Read, and cleaned up in the CLI/stream finally. See PLUGIN_SCHEMA §2.1.3.
  private _chatImageRunDir: string | null = null;
  private _chatImagePaths: string[] = [];
  private vaultRoot: string;
  private persistSettings?: () => Promise<void>;
  private mcpManager?: MCPManager;
  private beforeProviderLaunch?: () => void | Promise<void>;
  /** Plugin-executed read-only PDF reader (v0.41.0). Never an MCP tool. */
  private localPdfToolRunner?: LocalPdfToolRunner;

  constructor(
    settings: PluginSettings,
    auth: CLIAuthResolver,
    vaultRoot: string = "",
    persistSettings?: () => Promise<void>,
    mcpManager?: MCPManager,
    beforeProviderLaunch?: () => void | Promise<void>
  ) {
    this.settings = settings;
    this.auth = auth;
    this.vaultRoot = vaultRoot;
    this.persistSettings = persistSettings;
    this.mcpManager = mcpManager;
    this.beforeProviderLaunch = beforeProviderLaunch;
    // Best-effort startup sweep of crash-leftover chat image temp dirs (v0.28.0).
    this.sweepStaleChatImages();
  }

  /** Install the read-only PDF page reader (v0.41.0). See PLUGIN_SCHEMA §13.7. */
  setLocalPdfToolRunner(runner: LocalPdfToolRunner | undefined): void {
    this.localPdfToolRunner = runner;
  }

  /**
   * Execute one local PDF tool call. Every failure mode — unavailable runner,
   * bad arguments, out-of-range page, exhausted budget, or a document swapped
   * mid-request — becomes a typed tool message the model can answer around.
   * A changed document identity must NEVER be resolved against the new
   * document, so it fails rather than silently reading a different PDF.
   */
  private async runLocalPdfTool(
    name: string,
    rawArgs: string,
    runner: LocalPdfToolRunner | undefined,
    captured: LocalPdfToolContext | undefined,
    budget: number,
  ): Promise<{ content: string; pagesFetched: number }> {
    if (!runner || !captured) {
      return { content: "Error: the PDF page reader is not available.", pagesFetched: 0 };
    }
    if (runner.describeContext().documentId !== captured.documentId) {
      return {
        content:
          "Error: the open document changed during this request; the page " +
          "reader is no longer valid. Answer from the context you already have.",
        pagesFetched: 0,
      };
    }

    const parsed = parseLocalPdfToolCall(name, rawArgs, captured);
    if (parsed.kind === "error") {
      return { content: `Error (${parsed.code}): ${parsed.message}`, pagesFetched: 0 };
    }

    try {
      if (parsed.kind === "fetch_page") {
        if (budget <= 0) {
          return {
            content:
              "Error (budget_exhausted): no further page reads are available " +
              "for this question. Answer from the pages you already have.",
            pagesFetched: 0,
          };
        }
        const text = await runner.fetchPage(parsed.pageNum);
        if (!text?.trim()) {
          return {
            content: `Error (not_found): page ${parsed.pageNum} has no extractable text.`,
            pagesFetched: 1,
          };
        }
        return { content: `Page ${parsed.pageNum}:\n${text.trim()}`, pagesFetched: 1 };
      }

      const hits = await runner.searchAnchor(parsed.query, LOCAL_PDF_SEARCH_TOP_K);
      return { content: formatAnchorHits(hits), pagesFetched: 0 };
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      return { content: `Error: PDF reader failed: ${detail}`, pagesFetched: 0 };
    }
  }

  updateSettings(settings: PluginSettings): void {
    this.settings = settings;
  }

  /** Abort the foreground request selected by the active UI surface. */
  abort(): void {
    this.foregroundRequestController?.abort();
  }

  private beginRequest(ownerSignal?: AbortSignal): AbortController {
    const controller = new AbortController();
    if (ownerSignal) {
      const abortFromOwner = () => controller.abort(ownerSignal.reason);
      if (ownerSignal.aborted) {
        abortFromOwner();
      } else {
        ownerSignal.addEventListener("abort", abortFromOwner, { once: true });
        this.requestAbortCleanup.set(controller, () => {
          ownerSignal.removeEventListener("abort", abortFromOwner);
        });
      }
    }
    if (!ownerSignal) {
      this.foregroundRequestControllers.add(controller);
      this.foregroundRequestController = controller;
    }
    return controller;
  }

  private endRequest(controller: AbortController): void {
    this.requestAbortCleanup.get(controller)?.();
    this.requestAbortCleanup.delete(controller);
    this.foregroundRequestControllers.delete(controller);
    if (this.foregroundRequestController === controller) {
      const remaining = Array.from(this.foregroundRequestControllers);
      this.foregroundRequestController = remaining[remaining.length - 1] ?? null;
    }
  }

  private withAbort<T>(operation: () => Promise<T>, signal: AbortSignal): Promise<T> {
    if (signal.aborted) {
      return Promise.reject(new DOMException("aborted", "AbortError"));
    }
    return new Promise<T>((resolve, reject) => {
      const onAbort = () => reject(new DOMException("aborted", "AbortError"));
      signal.addEventListener("abort", onAbort, { once: true });
      if (signal.aborted) {
        signal.removeEventListener("abort", onAbort);
        reject(new DOMException("aborted", "AbortError"));
        return;
      }
      let operationPromise: Promise<T>;
      try {
        operationPromise = operation();
      } catch (error) {
        signal.removeEventListener("abort", onAbort);
        reject(error);
        return;
      }
      operationPromise.then(
        (value) => {
          signal.removeEventListener("abort", onAbort);
          resolve(value);
        },
        (error) => {
          signal.removeEventListener("abort", onAbort);
          reject(error);
        },
      );
    });
  }

  /** Test MCP Connection */
  async testMcpConnection(serverName: string): Promise<{ name: string; version: string }> {
    return new Promise((resolve, reject) => {
      const rawServer = this.settings.mcpServers.find((s) => s.name === serverName);
      if (!rawServer) {
        return reject(new Error(`Server ${serverName} not found in settings.`));
      }

      if (!rawServer.command) {
        return reject(new Error("Command is empty."));
      }

      const serverConfig = this.processMcpServer(rawServer);
      const env = this.getAugmentedEnv(serverConfig.env);

      const child = spawn(serverConfig.command, serverConfig.args, { env });

      let stdoutBuffer = "";
      let stderrBuffer = "";
      let resolved = false;

      const timeout = setTimeout(() => {
        if (!resolved) {
          resolved = true;
          child.kill();
          reject(new Error("Connection timed out after 5 seconds."));
        }
      }, 5000);

      child.stdout.on("data", (data) => {
        if (resolved) return;
        stdoutBuffer += data.toString();
        
        // Try to parse out the first complete JSON object (MCP initialize response)
        const lines = stdoutBuffer.split("\n");
        for (const line of lines) {
          if (!line.trim()) continue;
          try {
            const parsed = JSON.parse(line);
            if (parsed.jsonrpc === "2.0" && parsed.id === 1) {
              resolved = true;
              clearTimeout(timeout);
              child.kill();
              
              const info = parsed.result?.serverInfo || { name: "Unknown", version: "Unknown" };
              resolve({ name: info.name, version: info.version });
              return;
            }
          } catch (e) {
            // Incomplete JSON line or non-JSON output, keep buffering
          }
        }
      });

      child.stderr.on("data", (data) => {
        stderrBuffer += data.toString();
      });

      child.on("error", (err) => {
        if (!resolved) {
          resolved = true;
          clearTimeout(timeout);
          reject(new Error(`Failed to start process: ${err.message}`));
        }
      });

      child.on("close", (code) => {
        if (!resolved) {
          resolved = true;
          clearTimeout(timeout);
          reject(new Error(`Process exited with code ${code}. Stderr: ${stderrBuffer.substring(0, 200)}`));
        }
      });

      const initMessage = {
        jsonrpc: "2.0",
        id: 1,
        method: "initialize",
        params: {
          protocolVersion: "2024-11-05",
          capabilities: {},
          clientInfo: {
            name: "incurator-obsidian-agent-test",
            version: "1.0.0"
          }
        }
      };
      
      child.stdin?.write(JSON.stringify(initMessage) + "\n");
    });
  }

  /**
   * Stream a chat completion, calling onChunk for each token.
   * Returns the full assembled response text.
   */
  async streamChat(
    messages: LLMMessage[],
    onChunk: (chunk: StreamChunk) => void,
    opts?: { toolPolicy?: ToolPolicy; signal?: AbortSignal }
  ): Promise<string> {
    const controller = this.beginRequest(opts?.signal);
    try {
      if (controller.signal.aborted) {
        onChunk({ text: "", done: true });
        return "";
      }
      await this.beforeProviderLaunch?.();
      if (controller.signal.aborted) {
        onChunk({ text: "", done: true });
        return "";
      }
      const toolPolicy: ToolPolicy = opts?.toolPolicy ?? "auto";
    // Capture the manager once so its presence is stable across the async tool
    // loop below (no state drift if this.mcpManager is swapped mid-flight) and so
    // TypeScript narrows it to non-null after the early return — no `!` needed.
    const mcpManager = this.mcpManager;
    const useCli = this.shouldUseCli(messages);
    // Single decision point PER TOOL FAMILY. `toolPolicy: "none"` funnels into
    // the SAME no-tools single-turn path as CLI providers and the no-manager
    // case, so the tool-free paths can never diverge. `"local-only"` (the Quick
    // Query popover since v0.41.0) refuses MCP identically but may still carry
    // the plugin-executed PDF reader — see PLUGIN_SCHEMA §13.7.
    const injectTools = shouldInjectMcpTools(toolPolicy, Boolean(mcpManager), useCli);
    // Capture the runner AND its resolved context once per request, mirroring
    // the mcpManager capture above: every round must resolve against the same
    // document identity even if the active PDF changes mid-flight.
    const localRunner = this.localPdfToolRunner;
    const injectLocal = shouldInjectLocalTools(toolPolicy, Boolean(localRunner), useCli);
    const localContext: LocalPdfToolContext | undefined =
      injectLocal && localRunner ? localRunner.describeContext() : undefined;
    const localTools = localContext ? buildLocalPdfTools(localContext) : [];

    if ((!injectTools || !mcpManager) && localTools.length === 0) {
      const { text } = await this._streamChatSingleTurn(
        messages,
        onChunk,
        undefined,
        toolPolicy,
        controller,
      );
      return text;
    }

    const rawTools = injectTools && mcpManager ? mcpManager.getAllTools() : [];
    const { tools, routes } = buildMcpToolExposure(rawTools);
    let localFetchBudget = LOCAL_PDF_FETCH_BUDGET;

    let currentMessages = [...messages];
    let fullFinalText = "";
    const MAX_RECURSION = 5;
    let iteration = 0;

    while (iteration < MAX_RECURSION) {
      iteration++;
      const isLastTurn = iteration === MAX_RECURSION;
      // Don't pass tools if it's the last turn to force a final answer
      const exposed = [...tools, ...localTools];
      const activeTools = isLastTurn ? undefined : (exposed.length > 0 ? exposed : undefined);

      const { text, tool_calls } = await this._streamChatSingleTurn(
        currentMessages,
        onChunk,
        activeTools,
        toolPolicy,
        controller,
      );
      fullFinalText += text;

      if (!tool_calls || tool_calls.length === 0) {
        break;
      }

      // Append assistant's tool call message
      currentMessages.push({
        role: "assistant",
        content: text,
        tool_calls: tool_calls,
      });

      // Execute tools
      for (const tc of tool_calls) {
        onChunk({ text: `\n> Running tool: ${tc.function.name}...\n`, done: false, eventType: "status" });
        try {
          // Local (plugin-executed) tools are routed before MCP so a local name
          // can never reach mcpManager, and so their failures stay typed
          // messages the model can answer around instead of thrown turns.
          if (isLocalPdfToolName(tc.function.name)) {
            const budget = localFetchBudget;
            const outcome = await this.runLocalPdfTool(
              tc.function.name,
              tc.function.arguments || "{}",
              localRunner,
              localContext,
              budget,
            );
            localFetchBudget -= outcome.pagesFetched;
            currentMessages.push({
              role: "tool",
              tool_call_id: tc.id,
              name: tc.function.name,
              content: outcome.content,
            });
            continue;
          }

          const route = routes.get(tc.function.name);
          if (!route) throw new Error(`Unknown MCP tool: ${tc.function.name}`);
          if (!mcpManager) throw new Error(`No MCP manager for tool: ${tc.function.name}`);

          let args = {};
          try {
            args = JSON.parse(tc.function.arguments || "{}");
          } catch (e) {
            throw new Error(`Invalid JSON arguments: ${tc.function.arguments}`);
          }

          const result = await mcpManager.callTool(route.serverName, route.toolName, args);
          const resultContent = result.content.map(c => c.text).join("\n");
          
          currentMessages.push({
            role: "tool",
            tool_call_id: tc.id,
            name: tc.function.name,
            content: resultContent,
          });
        } catch (e) {
          const errStr = e instanceof Error ? e.message : String(e);
          currentMessages.push({
            role: "tool",
            tool_call_id: tc.id,
            name: tc.function.name,
            content: `Error executing tool: ${errStr}`,
          });
        }
      }
    }

    return fullFinalText;
    } finally {
      this.endRequest(controller);
    }
  }

  private async _streamChatSingleTurn(
    messages: LLMMessage[],
    onChunk: (chunk: StreamChunk) => void,
    tools?: any[],
    toolPolicy: ToolPolicy = "auto",
    requestController?: AbortController,
  ): Promise<{ text: string; tool_calls?: any[] }> {
    const ownsController = requestController === undefined;
    const controller = requestController ?? this.beginRequest();
    try {
      const provider = this.settings.provider;

    if (this.shouldUseCli(messages)) {
      const text = await this.streamChatViaCli(
        messages,
        onChunk,
        toolPolicy,
        controller.signal,
      );
      return { text };
    }

    // For Ollama, refresh the adapter host from current settings
    if (provider === "ollama") {
      ADAPTERS.ollama = new OllamaAdapter(this.settings.ollamaHost || "http://localhost:11434");
    }

    const adapter = ADAPTERS[provider];
    const credential = provider === "ollama"
      ? { type: "bearer" as const, token: "" }
      : provider === "deepseek"
        ? { type: "bearer" as const, token: this.settings.deepseekApiKey || process.env.DEEPSEEK_API_KEY || "" }
      : await this.auth.resolveCredential(provider);

    // Guard: DeepSeek requires an API key — reject early before making a request
    // that will return a 400 error with a confusing "Invalid assistant message" error.
    if (provider === "deepseek" && !credential.token) {
      throw new Error(
        "DeepSeek API key is not set.\n" +
        "Go to Settings → AI Provider and enter your API key,\n" +
        "or set the DEEPSEEK_API_KEY environment variable."
      );
    }

    const url = adapter.buildUrl(this.settings.model);
    const headers = adapter.buildHeaders(credential);
    const body = adapter.buildBody(messages, true, tools);

    // Always inject the model into the body for HTTP providers
    (body as Record<string, unknown>).model = this.settings.model;

    // Use fetch for streaming (Obsidian's requestUrl doesn't support streaming)
    let fullText = "";
    let toolCallsMap = new Map<number, any>();

    try {
      let response: Response;
      try {
        response = await fetch(url, {
          method: "POST",
          headers,
          body: JSON.stringify(body),
          signal: controller.signal,
        });
      } catch (fetchErr) {
        if (isAbortError(fetchErr)) throw fetchErr;
        if (provider === "ollama") {
          throw new Error(
            `Ollama is not reachable at ${this.settings.ollamaHost || "http://localhost:11434"}.\n` +
            `Start it with: ollama serve`
          );
        }
        throw fetchErr;
      }

      if (!response.ok) {
        const errorText = await response.text();
        if (response.status === 401 || response.status === 403) {
          if (provider === "ollama") {
            throw new Error(`Ollama returned auth error ${response.status} — check your Ollama server config.`);
          }
          if (provider === "deepseek") {
            this.auth.invalidate(provider);
            throw new Error(`DeepSeek API authentication failed (${response.status}). Check DEEPSEEK_API_KEY.`);
          }
          this.auth.invalidate(provider);
          new Notice(`${provider} HTTP auth failed. Retrying through the provider CLI login session.`);
          const text = await this.streamChatViaCli(
            messages,
            onChunk,
            toolPolicy,
            controller.signal,
          );
          return { text };
        }
        throw new Error(`LLM API error ${response.status}: ${errorText.slice(0, 200)}`);
      }

      const reader = response.body?.getReader();
      if (!reader) {
        throw new Error("Response body is not readable");
      }

      const decoder = new TextDecoder();
      let buffer = "";

      let isReasoning = false;
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });

        // Process complete lines
        const lines = buffer.split("\n");
        buffer = lines.pop() || ""; // Keep incomplete line in buffer

        for (const line of lines) {
          if (!line.trim()) continue;
          const chunk = adapter.parseStreamChunk(line);
          if (chunk) {
            let chunkText = chunk.text;
            
            // Handle reasoning_content from DeepSeek/Ollama
            if (chunk.reasoning_content !== undefined && chunk.reasoning_content !== null) {
              if (!isReasoning && chunk.reasoning_content) {
                isReasoning = true;
                chunkText = "<think>\n" + chunk.reasoning_content;
              } else {
                chunkText = chunk.reasoning_content + chunkText;
              }
            } else if (isReasoning && chunk.text) {
              // Transition from reasoning to normal text
              isReasoning = false;
              chunkText = "\n</think>\n\n" + chunk.text;
            }

            fullText += chunkText;
            
            if (chunk.tool_calls) {
              for (const tc of chunk.tool_calls) {
                const tcId = tc.id || `call_${Math.random().toString(36).substring(2, 9)}`;
                if (!toolCallsMap.has(tc.index)) {
                  toolCallsMap.set(tc.index, { id: tcId, type: tc.type || "function", function: { name: tc.function?.name || "", arguments: tc.function?.arguments || "" } });
                } else {
                  const existing = toolCallsMap.get(tc.index);
                  if (tc.function?.arguments) existing.function.arguments += tc.function.arguments;
                }
              }
            }
            
            // Re-emit chunk with formatted text
            onChunk({ ...chunk, text: chunkText });
            if (chunk.done) break;
          }
        }
      }

      // Process any remaining buffer
      if (buffer.trim()) {
        const chunk = adapter.parseStreamChunk(buffer);
        if (chunk) {
          let chunkText = chunk.text;
          if (chunk.reasoning_content !== undefined && chunk.reasoning_content !== null) {
            if (!isReasoning && chunk.reasoning_content) {
              isReasoning = true;
              chunkText = "<think>\n" + chunk.reasoning_content;
            } else {
              chunkText = chunk.reasoning_content + chunkText;
            }
          }
          fullText += chunkText;
          if (chunk.tool_calls) {
            for (const tc of chunk.tool_calls) {
              const tcId = tc.id || `call_${Math.random().toString(36).substring(2, 9)}`;
              if (!toolCallsMap.has(tc.index)) {
                toolCallsMap.set(tc.index, { id: tcId, type: tc.type || "function", function: { name: tc.function?.name || "", arguments: tc.function?.arguments || "" } });
              } else {
                const existing = toolCallsMap.get(tc.index);
                if (tc.function?.arguments) existing.function.arguments += tc.function.arguments;
              }
            }
          }
          onChunk({ ...chunk, text: chunkText });
        }
      }

      if (isReasoning) {
        // Ensure reasoning block is closed if the stream ends abruptly
        isReasoning = false;
        fullText += "\n</think>\n\n";
        onChunk({ text: "\n</think>\n\n", done: false });
      }

      // Ensure we send a done signal
      onChunk({ text: "", done: true });
    } catch (err: unknown) {
      if (isAbortError(err)) {
        onChunk({ text: "", done: true });
        return { text: fullText };
      }
      const msg = err instanceof Error ? err.message : String(err);
      if (isQuotaErrorMessage(msg)) {
        throw new Error(formatQuotaErrorMessage(provider, msg));
      }
      throw err;
    }

    const tool_calls = toolCallsMap.size > 0 ? Array.from(toolCallsMap.values()) : undefined;
    return { text: fullText, tool_calls };
    } finally {
      if (ownsController) this.endRequest(controller);
    }
  }

  /**
   * Non-streaming request (for inline edits where we need the full result).
   */
  async complete(
    messages: LLMMessage[],
    opts?: { model?: string; toolPolicy?: ToolPolicy; signal?: AbortSignal }
  ): Promise<string> {
    const controller = this.beginRequest(opts?.signal);
    try {
      if (controller.signal.aborted) {
        throw new DOMException("aborted", "AbortError");
      }
      await this.beforeProviderLaunch?.();
      if (controller.signal.aborted) {
        throw new DOMException("aborted", "AbortError");
      }
      const provider = this.settings.provider;
    // Per-call model override (v0.21.0): a task-specialized light model (e.g.
    // Convert-to-LaTeX) may run on a smaller model than the main chat `model`.
    // Empty/unset falls back to the configured model, preserving prior behavior.
    const model = opts?.model?.trim() || this.settings.model;
    const toolPolicy: ToolPolicy = opts?.toolPolicy ?? "auto";

    if (this.shouldUseCli(messages)) {
      return this.completeViaCli(messages, toolPolicy, model, controller.signal);
    }

    // Ollama uses fetch for non-streaming too (requestUrl may not reach localhost in all envs)
    if (provider === "ollama") {
      ADAPTERS.ollama = new OllamaAdapter(this.settings.ollamaHost || "http://localhost:11434");
      const adapter = ADAPTERS.ollama;
      const body = adapter.buildBody(messages, false);
      (body as Record<string, unknown>).model = model;
      try {
        const res = await fetch(adapter.buildUrl(model), {
          method: "POST",
          headers: adapter.buildHeaders({ type: "bearer", token: "" }),
          body: JSON.stringify(body),
          signal: controller.signal,
        });
        if (!res.ok) throw new Error(`Ollama error ${res.status}: ${await res.text()}`);
        return adapter.parseFullResponse(await res.json());
      } catch (err) {
        if (isAbortError(err)) throw err;
        const msg = err instanceof Error ? err.message : String(err);
        if (msg.includes("Failed to fetch") || msg.includes("ECONNREFUSED")) {
          throw new Error(`Ollama not reachable at ${this.settings.ollamaHost || "http://localhost:11434"}. Run: ollama serve`);
        }
        throw new Error(`Ollama request failed: ${msg}`);
      }
    }

    const adapter = ADAPTERS[provider];
    const credential = provider === "deepseek"
      ? { type: "bearer" as const, token: this.settings.deepseekApiKey || process.env.DEEPSEEK_API_KEY || "" }
      : await this.auth.resolveCredential(provider);

    let url = adapter.buildUrl(model);
    const headers = adapter.buildHeaders(credential);
    const body = adapter.buildBody(messages, false);

    // For Antigravity non-streaming, use generateContent instead of streamGenerateContent
    if (provider === "antigravity") {
      url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`;
    }

    (body as Record<string, unknown>).model = model;

    try {
      const response = await this.withAbort(
        () => requestUrl({
          url,
          method: "POST",
          headers,
          body: JSON.stringify(body),
        }),
        controller.signal,
      );

      return adapter.parseFullResponse(response.json);
    } catch (err: unknown) {
      if (isAbortError(err)) {
        throw err;
      }
      const msg = err instanceof Error ? err.message : String(err);
      if (msg.includes("401") || msg.includes("403")) {
        if (provider === "deepseek") {
          this.auth.invalidate(provider);
          throw new Error("DeepSeek API authentication failed. Check DEEPSEEK_API_KEY.");
        }
        this.auth.invalidate(provider);
        new Notice(`${provider} HTTP auth failed. Retrying through the provider CLI login session.`);
        return this.completeViaCli(messages, toolPolicy, model, controller.signal);
      }
      if (isQuotaErrorMessage(msg)) {
        throw new Error(formatQuotaErrorMessage(provider, msg));
      }
      throw new Error(`LLM request failed: ${msg}`);
    }
    } finally {
      this.endRequest(controller);
    }
  }

  private shouldUseCli(_messages: LLMMessage[]): boolean {
    if (this.settings.provider === "ollama" || this.settings.provider === "deepseek") return false;
    return true;
  }

  private streamChatViaCli(
    messages: LLMMessage[],
    onChunk: (chunk: StreamChunk) => void,
    toolPolicy: ToolPolicy = "auto",
    signal: AbortSignal,
  ): Promise<string> {
    return new Promise((resolve, reject) => {
      if (signal.aborted) {
        onChunk({ text: "", done: true });
        resolve("");
        return;
      }
      const provider = this.settings.provider;
      const prompt = this.messagesToCliPrompt(messages);
      const imageRunDir = this._chatImageRunDir;
      let cwd: string;
      let outputFile: string | undefined;
      let command: string;
      let args: string[];
      let env: Record<string, string> | undefined;
      let stdin: string | undefined;
      try {
        cwd = this.getCliCwd();
        outputFile =
          provider === "openai"
            ? join(
                cwd,
                `codex-output-${Date.now()}-${Math.random().toString(36).slice(2)}.txt`
              )
            : undefined;
        ({ command, args, env, stdin } = this.buildCliCommand(
          prompt,
          outputFile,
          provider,
          true,
          toolPolicy
        ));
      } catch (err) {
        // Synchronous setup failed before any child spawn, so neither "close"
        // nor "error" will fire — clean the image dir here so it never leaks.
        this.cleanupChatImageDir(imageRunDir);
        reject(err instanceof Error ? err : new Error(String(err)));
        return;
      }

      let fullOutput = "";
      let fullStdout = "";
      let fullStderr = "";

      // State for CLI JSON/event parsing
      let jsonBuffer = "";
      let codexJsonBuffer = "";
      let inThinking = false;
      let prevThinkingLen = 0;
      let prevTextLen = 0;
      const seenToolIds = new Map<string, string>();
      let claudeResult = "";
      let claudeIsError = false;
      let statusBlockOpen = false;
      let lastCodexStatus = "";
      let codexAnswerText = "";
      let observedUsage: Partial<ProviderUsage> | undefined;

      const emitCodexStatus = (status: string) => {
        if (!status || status === lastCodexStatus) return;
        lastCodexStatus = status;
        if (!statusBlockOpen) {
          onChunk({ text: "<thinking>\n", done: false });
          statusBlockOpen = true;
        }
        onChunk({ text: `\n- ${status}`, done: false });
      };

      const closeStatusBlock = () => {
        if (statusBlockOpen) {
          onChunk({ text: "\n</thinking>\n\n", done: false });
          statusBlockOpen = false;
          inThinking = false;
        }
      };

      const emitMcpAvailability = () => {
        const enabledServers = this.settings.mcpServers
          .filter((server) => server.enabled && server.name.trim())
          .map((server) => server.name.trim());
        if (enabledServers.length === 0) return;
        emitCodexStatus(`MCP servers available: ${enabledServers.join(", ")}`);
      };

      const processClaudeJsonLine = (line: string) => {
        if (!line.trim()) return;
        let event: Record<string, unknown>;
        try {
          event = JSON.parse(line);
        } catch {
          return;
        }

        if (event.type === "assistant") {
          const content = (event.message as Record<string, unknown>)?.content as Array<Record<string, unknown>> || [];
          for (const block of content) {
            if (block.type === "thinking") {
              const thinking = (block.thinking as string) || "";
              if (thinking.length > prevThinkingLen) {
                if (!inThinking) {
                  if (!statusBlockOpen) {
                    onChunk({ text: "<thinking>\n", done: false });
                    statusBlockOpen = true;
                  } else {
                    onChunk({ text: "\n\n", done: false });
                  }
                  inThinking = true;
                }
                onChunk({ text: thinking.slice(prevThinkingLen), done: false });
                prevThinkingLen = thinking.length;
              }
            } else if (block.type === "tool_use") {
              const toolId = (block.id as string) || "";
              if (!seenToolIds.has(toolId)) {
                const toolName = (block.name as string) || "tool";
                seenToolIds.set(toolId, toolName);
                if (inThinking) {
                  inThinking = false;
                }
                if (!statusBlockOpen) {
                  onChunk({ text: "<thinking>\n", done: false });
                  statusBlockOpen = true;
                }
                const input = block.input as Record<string, unknown> || {};
                // Format args as compact JSON, capped to avoid huge blocks
                const argsJson = JSON.stringify(input, null, 2);
                const argsDisplay = argsJson.length > 800 ? argsJson.slice(0, 800) + "\n  ..." : argsJson;
                onChunk({ text: `\n\n🔧 **${toolName}**\n\`\`\`json\n${argsDisplay}\n\`\`\``, done: false });
              }
            } else if (block.type === "text") {
              const text = (block.text as string) || "";
              if (text.length > prevTextLen) {
                if (inThinking || statusBlockOpen) {
                  onChunk({ text: "\n</thinking>\n\n", done: false });
                  inThinking = false;
                  statusBlockOpen = false;
                }
                onChunk({ text: text.slice(prevTextLen), done: false });
                prevTextLen = text.length;
              }
            }
          }
        } else if (event.type === "user") {
          const content = (event.message as Record<string, unknown>)?.content as Array<Record<string, unknown>> || [];
          for (const block of content) {
            if (block.type === "tool_result") {
              const toolId = (block.tool_use_id as string) || "tool";
              const toolName = seenToolIds.get(toolId) || "tool";
              let resultText = "";
              if (typeof block.content === "string") {
                resultText = block.content;
              } else if (Array.isArray(block.content)) {
                resultText = JSON.stringify(block.content, null, 2);
              } else if (event.tool_use_result) {
                resultText = JSON.stringify(event.tool_use_result, null, 2);
              }
              
              resultText = formatMcpToolResultForDisplay(toolName, resultText);
              if (!statusBlockOpen) {
                onChunk({ text: "<thinking>\n", done: false });
                statusBlockOpen = true;
              }
              onChunk({ text: `\n\n✅ **${toolName}** result:\n\`\`\`\n${resultText}\n\`\`\``, done: false });
            }
          }
        } else if (event.type === "result") {
          if (statusBlockOpen || inThinking) {
            onChunk({ text: "\n</thinking>\n\n", done: false });
            inThinking = false;
            statusBlockOpen = false;
          }
          claudeResult = (event.result as string) || "";
          claudeIsError = (event.is_error as boolean) || false;
          observedUsage = this.mergeUsage(observedUsage, this.extractUsage(event));
        }
      };

      if (provider === "openai") {
        emitCodexStatus(`Preparing context for ${this.settings.model}`);
        emitCodexStatus("Starting Codex CLI");
      } else if (provider === "antigravity") {
        emitCodexStatus("Thinking... (Antigravity is generating the full response)");
      }
      emitMcpAvailability();

      const child = spawn(command, args, {
        cwd,
        env: this.getAugmentedEnv(env),
        stdio: ["pipe", "pipe", "pipe"],
        windowsHide: true,
      });

      if (stdin !== undefined) {
        child.stdin?.end(stdin);
      } else {
        child.stdin?.end();
      }

      const abortChild = () => child.kill();
      if (signal.aborted) abortChild();
      else signal.addEventListener("abort", abortChild, { once: true });
      const detachAbort = () => signal.removeEventListener("abort", abortChild);

      const stdoutDecoder = new TextDecoder("utf-8");
      const stderrDecoder = new TextDecoder("utf-8");

      const processStdoutText = (text: string) => {
        if (!text) return;
        fullOutput += text;

        if (provider === "claude") {
          jsonBuffer += text;
          const lines = jsonBuffer.split("\n");
          jsonBuffer = lines.pop() || "";
          for (const line of lines) {
            processClaudeJsonLine(line);
          }
        } else if (provider === "openai") {
          codexJsonBuffer += text;
          const lines = codexJsonBuffer.split("\n");
          codexJsonBuffer = lines.pop() || "";
          for (const line of lines) {
            observedUsage = this.mergeUsage(observedUsage, this.extractUsageFromJsonLine(line));
            const status = this.summarizeCodexJsonLine(line);
            if (status && !codexAnswerText) emitCodexStatus(status);
            const answerText = this.extractCodexAnswerTextFromJsonLine(line);
            if (answerText && answerText.length > codexAnswerText.length) {
              closeStatusBlock();
              onChunk({
                text: answerText.slice(codexAnswerText.length),
                done: false,
              });
              codexAnswerText = answerText;
            }
          }
        } else {
          closeStatusBlock();
          onChunk({ text, done: false });
        }
      };

      child.stdout?.on("data", (data) => {
        const text = stdoutDecoder.decode(data, { stream: true });
        
        fullStdout += text;
        const authKeywords = [
          "Authentication required",
          "paste the authorization code",
          "You must login",
          "claude login",
          "codex login",
          "Session expired"
        ];
        if (authKeywords.some(kw => fullStdout.includes(kw))) {
          child.kill();
          reject(new Error(`CLI authentication required. Please go to Settings -> Incurator -> ${provider} and click 'Login' to authenticate interactively.`));
          return;
        }

        processStdoutText(text);
      });

      child.stderr?.on("data", (data) => {
        const text = stderrDecoder.decode(data, { stream: true });
        
        fullStderr += text;
        const authKeywords = [
          "Authentication required",
          "paste the authorization code",
          "You must login",
          "claude login",
          "codex login",
          "Session expired"
        ];
        if (authKeywords.some(kw => fullStderr.includes(kw))) {
          child.kill();
          reject(new Error(`CLI authentication required. Please go to Settings -> Incurator -> ${provider} and click 'Login' to authenticate interactively.`));
          return;
        }

        // Token/quota exhausted mid-stream → fail fast instead of letting the
        // CLI spin until its print-timeout with no answer.
        if (isQuotaErrorMessage(fullStderr)) {
          child.kill();
          reject(new Error(formatQuotaErrorMessage(provider, fullStderr.trim())));
          return;
        }

        // For non-JSON stdout providers, intercept stderr as thinking updates.
        // agy can occasionally route the final answer through stderr; only
        // display known status/progress lines here and recover answer-like
        // stderr content on process close if stdout stayed empty.
        if (provider === "antigravity") {
          const lines = text.split("\n");
          for (const line of lines) {
            const cleanLine = line.trim();
            if (cleanLine && isAntigravityStatusLine(cleanLine)) {
              emitCodexStatus(cleanLine);
            }
          }
        } else if (provider !== "claude" && provider !== "openai") {
          const lines = text.split("\n");
          for (const line of lines) {
            const cleanLine = line.trim();
            if (cleanLine) {
              emitCodexStatus(cleanLine);
            }
          }
        }
      });

      child.on("close", (code) => {
        detachAbort();
        // v0.28.0: clean the per-call image dir on every terminal path (success,
        // error-exit, and abort → kill → close all flow through here).
        this.cleanupChatImageDir(imageRunDir);
        processStdoutText(stdoutDecoder.decode());
        fullStderr += stderrDecoder.decode();

        if (provider === "claude") {
          // Flush remaining buffer
          if (jsonBuffer.trim()) processClaudeJsonLine(jsonBuffer);
          if (inThinking || statusBlockOpen) onChunk({ text: "</thinking>\n\n", done: false });
          onChunk({ text: "", done: true });
          if (claudeIsError) {
            reject(new Error(`claude CLI error: ${claudeResult}`));
          } else {
            this.recordUsage(provider, observedUsage);
            resolve(claudeResult || fullOutput);
          }
          return;
        }

        if (provider === "openai" && codexJsonBuffer.trim()) {
          observedUsage = this.mergeUsage(
            observedUsage,
            this.extractUsageFromJsonLine(codexJsonBuffer)
          );
          const answerText = this.extractCodexAnswerTextFromJsonLine(codexJsonBuffer);
          if (answerText && answerText.length > codexAnswerText.length) {
            closeStatusBlock();
            onChunk({
              text: answerText.slice(codexAnswerText.length),
              done: false,
            });
            codexAnswerText = answerText;
          }
          const status = this.summarizeCodexJsonLine(codexJsonBuffer);
          if (status && !codexAnswerText) emitCodexStatus(status);
        }

        let recoveredAntigravityAnswer = "";
        if (outputFile && existsSync(outputFile)) {
          try {
            fullOutput = readFileSync(outputFile, "utf-8").trim();
            unlinkSync(outputFile);
          } catch (e) {
            // ignore
          }
        } else {
          fullOutput = this.cleanCliOutput(provider, fullOutput);
          if (provider === "antigravity" && fullOutput.trim().length === 0) {
            recoveredAntigravityAnswer = extractAntigravityAnswerFromStderr(fullStderr);
            if (recoveredAntigravityAnswer) {
              fullOutput = recoveredAntigravityAnswer;
            }
          }
        }

        if (provider === "openai") {
          closeStatusBlock();
          if (!codexAnswerText) {
            onChunk({ text: fullOutput, done: false });
          }
        } else if (provider === "antigravity" && recoveredAntigravityAnswer) {
          closeStatusBlock();
          onChunk({ text: recoveredAntigravityAnswer, done: false });
        } else {
          // antigravity: ensure thinking block is closed before done
          closeStatusBlock();
        }

        const trimmedOutput = fullOutput.trim();
        // The user-visible answer: codex streams via codexAnswerText, other CLI
        // providers stream fullOutput. Use this to decide "did we answer at all".
        const emittedAnswer =
          provider === "openai"
            ? codexAnswerText.trim() || trimmedOutput
            : trimmedOutput;
        const aborted = signal.aborted;
        const combinedForQuota = `${fullStderr}\n${fullOutput}`;

        if (aborted) {
          onChunk({ text: "", done: true });
          this.recordUsage(provider, observedUsage);
          resolve(fullOutput);
        } else if (isQuotaErrorMessage(combinedForQuota)) {
          // Provider token/quota exhausted — surface a real error instead of
          // spinning forever or silently returning an empty answer.
          reject(
            new Error(
              formatQuotaErrorMessage(
                provider,
                fullStderr.trim() || trimmedOutput || "quota or capacity exhausted"
              )
            )
          );
        } else if (code !== 0 && emittedAnswer.length === 0) {
          const errText = fullStderr.trim();
          reject(new Error(`${provider} CLI failed: ${errText.slice(0, 500)}`));
        } else if (emittedAnswer.length === 0) {
          // Exit 0 but no answer text — e.g. agy shows "Thinking…" then ends with
          // nothing. Usually quota/capacity, a timeout, or an empty model
          // response. Reject so the UI shows an error instead of an empty bubble
          // or an endless spinner.
          const errText = fullStderr.trim();
          reject(
            new Error(
              `${provider} returned no answer (empty response).` +
                (errText ? `\n\n${errText.slice(0, 400)}` : "") +
                `\n\nThis usually means the provider quota/capacity is exhausted, the request timed out, or the model returned nothing. Switch provider/model or retry after quota resets.`
            )
          );
        } else {
          onChunk({ text: "", done: true });
          this.recordUsage(provider, observedUsage);
          resolve(fullOutput);
        }
      });

      child.on("error", (err) => {
        detachAbort();
        // spawn failure may fire without a "close"; clean the image dir here too.
        this.cleanupChatImageDir(imageRunDir);
        const msg = err instanceof Error ? err.message : String(err);
        if (msg.includes("ENOENT")) {
          reject(
            new Error(
              `${provider} CLI "${command}" is not installed or not found on PATH.\n\nInstall the CLI first, then retry.`
            )
          );
        } else {
          reject(
            new Error(
              `${provider} CLI request failed: ${msg}\n\nRun the provider CLI login again, then retry.`
            )
          );
        }
      });
    });
  }

  private summarizeToolInput(toolName: string, input: Record<string, unknown>): string {
    const lower = toolName.toLowerCase();
    if (lower === "bash") return `\`${String(input.command || "").slice(0, 120)}\``;
    if (lower === "read") return String(input.file_path || "").split("/").pop() || "";
    if (lower === "write" || lower === "edit") return String(input.file_path || "").split("/").pop() || "";
    if (lower === "websearch") return `"${String(input.query || "").slice(0, 80)}"`;
    if (lower === "webfetch") return String(input.url || "").slice(0, 80);
    // MCP tools: mcp_<server>_<method> → show method + first value
    const keys = Object.keys(input);
    if (keys.length === 0) return "";
    const first = String(input[keys[0]] || "").slice(0, 80);
    return first ? `${keys[0]}="${first}"` : "";
  }

  private summarizeCodexJsonLine(line: string): string | null {
    if (!line.trim()) return null;
    let event: Record<string, unknown>;
    try {
      event = JSON.parse(line) as Record<string, unknown>;
    } catch {
      return null;
    }

    const msg =
      event.msg && typeof event.msg === "object"
        ? (event.msg as Record<string, unknown>)
        : undefined;
    const type = String(event.type || msg?.type || "");
    const item = (event.item || msg || event) as Record<string, unknown>;
    const itemType = String(item.type || "");
    const toolName = this.findNestedString(item, ["name", "tool_name", "command"]);

    if (type.includes("turn.started")) return "Planning the answer";
    if (type.includes("turn.completed")) return "Composing final response";
    if (type.includes("error")) return "Codex reported an error";
    if (type.includes("item.started") || type.includes("item.completed")) {
      if (itemType.includes("reasoning")) return "Reasoning over the supplied context";
      if (itemType.includes("tool") || toolName) {
        // Show actual tool name and arguments for MCP tool calls
        const isMcp = toolName && toolName.startsWith("mcp_");
        const callArgs = this.findNestedString(item, ["arguments", "input", "params"]);
        if (isMcp && callArgs) {
          return `🔧 **${toolName}** \`${callArgs.slice(0, 120)}\``;
        }
        return `Using tool: **${toolName || "unknown"}**`;
      }
      if (itemType.includes("message")) return "Drafting response text";
    }
    // Tool output / result events
    if (type.includes("tool_result") || type.includes("tool_output")) {
      const outputVal = this.findNestedString(item, ["output", "result", "content"]);
      const name = toolName || "tool";
      return outputVal ? `✅ **${name}** → \`${outputVal.slice(0, 120)}\`` : `✅ **${name}** returned`;
    }

    return null;
  }

  private extractCodexAnswerTextFromJsonLine(line: string): string | null {
    if (!line.trim()) return null;
    let event: Record<string, unknown>;
    try {
      event = JSON.parse(line) as Record<string, unknown>;
    } catch {
      return null;
    }

    const msg =
      event.msg && typeof event.msg === "object"
        ? (event.msg as Record<string, unknown>)
        : undefined;
    const item = (event.item ||
      msg?.item ||
      msg ||
      event) as Record<string, unknown>;

    return this.extractAssistantMessageText(item);
  }

  private extractAssistantMessageText(item: Record<string, unknown>): string | null {
    const itemType = String(item.type || "").toLowerCase();
    if (
      itemType.includes("reasoning") ||
      itemType.includes("tool") ||
      itemType.includes("function") ||
      itemType.includes("command")
    ) {
      return null;
    }

    const directText = item.text;
    if (typeof directText === "string" && directText.trim()) return directText;

    const directContent = item.content;
    if (typeof directContent === "string" && directContent.trim()) return directContent;
    if (Array.isArray(directContent)) {
      const text = directContent
        .map((block) => {
          if (!block || typeof block !== "object") return "";
          const record = block as Record<string, unknown>;
          const blockType = String(record.type || "").toLowerCase();
          if (
            blockType &&
            !blockType.includes("text") &&
            !blockType.includes("message") &&
            !blockType.includes("output")
          ) {
            return "";
          }
          return typeof record.text === "string"
            ? record.text
            : typeof record.content === "string"
              ? record.content
              : "";
        })
        .join("");
      if (text.trim()) return text;
    }

    const message = item.message;
    if (message && typeof message === "object") {
      return this.extractAssistantMessageText(message as Record<string, unknown>);
    }

    return null;
  }

  private findNestedString(value: unknown, keys: string[]): string | null {
    if (!value || typeof value !== "object") return null;
    const record = value as Record<string, unknown>;
    for (const key of keys) {
      const candidate = record[key];
      if (typeof candidate === "string" && candidate.trim()) {
        return candidate.trim().slice(0, 120);
      }
    }
    for (const child of Object.values(record)) {
      const found = this.findNestedString(child, keys);
      if (found) return found;
    }
    return null;
  }

  private async completeViaCli(
    messages: LLMMessage[],
    toolPolicy: ToolPolicy = "auto",
    model = this.settings.model,
    signal?: AbortSignal,
  ): Promise<string> {
    if (signal?.aborted) {
      throw new DOMException("aborted", "AbortError");
    }
    const provider = this.settings.provider;
    const prompt = this.messagesToCliPrompt(messages);
    const imageRunDir = this._chatImageRunDir;
    const cwd = this.getCliCwd();
    const outputFile =
      provider === "openai"
        ? join(
            cwd,
            `codex-output-${Date.now()}-${Math.random().toString(36).slice(2)}.txt`
          )
        : undefined;
    const { command, args, env } = this.buildCliCommand(
      prompt,
      outputFile,
      provider,
      false,
      toolPolicy,
      model,
    );

    try {
      const { stdout, stderr } = await execFileAsync(command, args, {
        cwd,
        env: this.getAugmentedEnv(env),
        timeout: CLI_TIMEOUT_MS,
        maxBuffer: 10 * 1024 * 1024,
        windowsHide: true,
        signal,
      });

      if (provider === "claude") {
        const result = this.extractClaudeJsonResult(stdout);
        if (result !== null) {
          this.recordUsage(provider, this.extractUsageFromJsonLines(stdout));
          return result;
        }
        throw new Error("claude CLI returned no result event.");
      }

      const output =
        outputFile && existsSync(outputFile)
          ? readFileSync(outputFile, "utf-8").trim()
          : this.cleanCliOutput(provider, stdout);
      if (output.length > 0) {
        this.recordUsage(provider, this.extractUsageFromJsonLines(stdout));
        return output;
      }

      const err = stderr.trim();
      if (err.length > 0) {
        throw new Error(err.slice(0, 500));
      }
      throw new Error(`${provider} CLI returned an empty response.`);
    } catch (err: unknown) {
      if (err instanceof Error && err.name === "AbortError") throw err;
      const msg = err instanceof Error ? err.message : String(err);
      if (msg.includes("ENOENT")) {
        throw new Error(
          `${provider} CLI is not installed or not found on PATH.\n\nInstall the CLI first, then retry.`
        );
      }
      throw new Error(
        `${provider} CLI request failed: ${msg}\n\nRun the provider CLI login again, then retry.`
      );
    } finally {
      if (outputFile && existsSync(outputFile)) {
        unlinkSync(outputFile);
      }
      this.cleanupChatImageDir(imageRunDir);
    }
  }

  private extractClaudeJsonResult(stdout: string): string | null {
    for (const line of stdout.trim().split("\n").reverse()) {
      try {
        const event = JSON.parse(line) as Record<string, unknown>;
        if (event.type === "result") {
          if (event.is_error) throw new Error(String(event.result || "claude error"));
          return String(event.result || "");
        }
      } catch (e) {
        if (e instanceof Error && e.message.startsWith("claude error")) throw e;
      }
    }
    return null;
  }

  private extractUsageFromJsonLines(stdout: string): Partial<ProviderUsage> | undefined {
    let usage: Partial<ProviderUsage> | undefined;
    for (const line of stdout.split("\n")) {
      usage = this.mergeUsage(usage, this.extractUsageFromJsonLine(line));
    }
    return usage;
  }

  private extractUsageFromJsonLine(line: string): Partial<ProviderUsage> | undefined {
    if (!line.trim()) return undefined;
    try {
      return this.extractUsage(JSON.parse(line) as Record<string, unknown>);
    } catch {
      return undefined;
    }
  }

  private extractUsage(event: Record<string, unknown>): Partial<ProviderUsage> | undefined {
    const usageCandidate =
      event.usage ||
      (event.message as Record<string, unknown> | undefined)?.usage ||
      (event.msg as Record<string, unknown> | undefined)?.usage ||
      (event.msg as Record<string, unknown> | undefined)?.usage_info;
    if (!usageCandidate || typeof usageCandidate !== "object") return undefined;

    const usage = usageCandidate as Record<string, unknown>;
    const inputTokens = this.readUsageNumber(usage, [
      "input_tokens",
      "inputTokens",
      "prompt_tokens",
      "promptTokens",
    ]);
    const cachedInputTokens = this.readUsageNumber(usage, [
      "cached_input_tokens",
      "cachedInputTokens",
      "cache_read_input_tokens",
      "cacheReadInputTokens",
    ]);
    const outputTokens = this.readUsageNumber(usage, [
      "output_tokens",
      "outputTokens",
      "completion_tokens",
      "completionTokens",
    ]);
    const reasoningOutputTokens = this.readUsageNumber(usage, [
      "reasoning_output_tokens",
      "reasoningOutputTokens",
      "reasoning_tokens",
      "reasoningTokens",
    ]);

    if (
      inputTokens === 0 &&
      cachedInputTokens === 0 &&
      outputTokens === 0 &&
      reasoningOutputTokens === 0
    ) {
      return undefined;
    }

    return {
      inputTokens,
      cachedInputTokens,
      outputTokens,
      reasoningOutputTokens,
    };
  }

  private readUsageNumber(usage: Record<string, unknown>, keys: string[]): number {
    for (const key of keys) {
      const value = usage[key];
      if (typeof value === "number" && Number.isFinite(value)) return value;
      if (typeof value === "string") {
        const parsed = Number(value);
        if (Number.isFinite(parsed)) return parsed;
      }
    }
    return 0;
  }

  private mergeUsage(
    current: Partial<ProviderUsage> | undefined,
    next: Partial<ProviderUsage> | undefined
  ): Partial<ProviderUsage> | undefined {
    if (!next) return current;
    return {
      inputTokens: (current?.inputTokens || 0) + (next.inputTokens || 0),
      cachedInputTokens:
        (current?.cachedInputTokens || 0) + (next.cachedInputTokens || 0),
      outputTokens: (current?.outputTokens || 0) + (next.outputTokens || 0),
      reasoningOutputTokens:
        (current?.reasoningOutputTokens || 0) +
        (next.reasoningOutputTokens || 0),
    };
  }

  private recordUsage(provider: LLMProvider, usage?: Partial<ProviderUsage>): void {
    const current = this.settings.providerUsage[provider] || {
      requests: 0,
      inputTokens: 0,
      cachedInputTokens: 0,
      outputTokens: 0,
      reasoningOutputTokens: 0,
    };
    this.settings.providerUsage[provider] = {
      requests: current.requests + 1,
      inputTokens: current.inputTokens + (usage?.inputTokens || 0),
      cachedInputTokens:
        current.cachedInputTokens + (usage?.cachedInputTokens || 0),
      outputTokens: current.outputTokens + (usage?.outputTokens || 0),
      reasoningOutputTokens:
        current.reasoningOutputTokens + (usage?.reasoningOutputTokens || 0),
      lastUsedAt: Date.now(),
    };
    this.persistSettings?.().catch(() => {
      // Usage accounting should never block the answer.
    });
  }

  private buildCliCommand(
    prompt: string,
    outputFile?: string,
    provider?: LLMProvider,
    preferStdin = false,
    toolPolicy: ToolPolicy = "auto",
    modelOverride?: string,
  ): {
    command: string;
    args: string[];
    env?: Record<string, string>;
    stdin?: string;
  } {
    const model = modelOverride?.trim() || this.settings.model;
    const p = provider ?? this.settings.provider;
    // FAIL-OPEN GUARD: toolPolicy defaults to "auto" (full tools). Any EPHEMERAL surface
    // (popover, inline preview, …) MUST pass a non-"auto" toolPolicy — a call site that
    // omits it silently gets the full tool surface. The predicate is exhaustive over
    // ToolPolicy (v0.41.0) so a newly added value is a compile error here rather than a
    // silent grant: "local-only" is ephemeral too, because the local PDF reader is
    // plugin-executed and hands the CLI agent no native tools or filesystem roots.
    const ephemeral = isEphemeralToolPolicy(toolPolicy); // popover / read-only surface
    // Only resolve allowed roots when they'll actually be used (non-ephemeral); the
    // tool-free popover path discards --add-dir, so skip the realpath I/O there.
    // v0.28.0: an image-bearing turn (image parts written by contentToCliText this
    // call) gets the scoped chat_images dir on --add-dir and Read removed from the
    // claude denylist; text-only turns keep the hardened no-Read denylist verbatim.
    const hasImage = this._chatImagePaths.length > 0;
    const imageRunDir = hasImage ? this._chatImageRunDir : null;
    const addDirs = ephemeral ? [] : this.allowedRoots().flatMap((r) => ["--add-dir", r]);
    if (!ephemeral && imageRunDir) addDirs.push("--add-dir", imageRunDir);
    let base: { command: string; args: string[]; env?: Record<string, string>; stdin?: string };
    switch (p) {
      case "antigravity": {
        this.syncAgyMcpConfig();
        const antigravityModelArgs = model ? ["--model", model] : [];
        const antigravityEffortArgs = this.settings.agentEffort
          ? ["--effort", this.settings.agentEffort]
          : [];
        // v0.23.0: NO blanket permission-skip / trust-workspace bypass. agy ignores
        // its own --sandbox (P0), so containment is the OS sandbox (wrapWithOsSandbox).
        base = {
          command: "agy",
          args: [
            "--print-timeout", `${Math.max(30, this.settings.antigravityPrintTimeoutSec || 300)}s`,
            // Keep --sandbox: in -p mode it auto-proceeds without the permission
            // prompt that would otherwise HANG (P0). It does NOT actually contain agy
            // (P0) — the OS sandbox (wrapWithOsSandbox) does. NO blanket skip / trust.
            "--sandbox",
            ...addDirs, // empty in ephemeral (tool-free popover) mode
            ...antigravityModelArgs,
            ...antigravityEffortArgs,
            "-p", prompt,
          ],
          env: {},
        };
        break;
      }
      case "claude": {
        const claudeMcpPath = this.syncClaudeMcpConfig();
        // claude has no deny-without-prompt dir sandbox → control via the TOOL SURFACE.
        // Popover: --tools "" (no tools). Sidechat: disable native fs/shell tools, keep
        // only the DB-scoped MCP curator tools (the plugin edit-loop handles vault edits).
        const toolArgs = ephemeral
          ? ["--tools", ""]
          : hasImage
            ? ["--disallowedTools", "Bash", "Write", "Edit", "WebFetch"]
            : ["--disallowedTools", "Bash", "Read", "Write", "Edit", "WebFetch"];
        // claude controls reads via the tool surface + --add-dir (no blanket
        // permission bypass here, so an out-of-add-dir Read would prompt/deny).
        // When Read is enabled for an image turn, confine --add-dir to JUST the
        // scoped image dir instead of the broad allowed roots (vault + Zotero),
        // so the v0.23.0 no-vault-read hardening still holds for image turns.
        const claudeAddDirs =
          !ephemeral && hasImage && imageRunDir
            ? ["--add-dir", imageRunDir]
            : addDirs;
        const claudeEffortArgs = this.settings.claudeEffort
          ? ["--effort", this.settings.claudeEffort]
          : [];
        base = {
          command: "claude",
          args: [
            "--mcp-config", claudeMcpPath,
            "-p", prompt,
            "--model", model,
            ...claudeEffortArgs,
            ...toolArgs,
            ...claudeAddDirs, // image turns: scoped image dir only (Read is enabled)
            "--output-format", "stream-json",
            "--verbose",
            "--include-partial-messages",
          ],
        };
        break;
      }
      case "openai":
      case "deepseek":
      case "ollama": {
        this.syncCodexMcpConfig();

        const extraEnv: Record<string, string> = {};
        if (provider === "deepseek") {
          extraEnv["OPENAI_API_BASE"] = "https://api.deepseek.com/v1";
          extraEnv["OPENAI_API_KEY"] = this.settings.deepseekApiKey || process.env.DEEPSEEK_API_KEY || "";
        } else if (provider === "ollama") {
          const host = this.settings.ollamaHost || "http://localhost:11434";
          extraEnv["OPENAI_API_BASE"] = `${host.replace(/\/$/, "")}/v1`;
          extraEnv["OPENAI_API_KEY"] = "ollama";
        }

        // Popover: read-only. Sidechat: workspace-write scoped to the allowed roots.
        const codexEffortArgs = this.settings.codexReasoningEffort
          ? ["-c", `model_reasoning_effort=${JSON.stringify(this.settings.codexReasoningEffort)}`]
          : [];
        base = {
          command: "codex",
          args: [
            "--profile", "obsidian",
            "exec",
            "-m", model,
            "--sandbox", ephemeral ? "read-only" : "workspace-write",
            ...addDirs, // empty in ephemeral (read-only popover) mode
            "--skip-git-repo-check",
            "--json",
            ...codexEffortArgs,
            ...(outputFile ? ["--output-last-message", outputFile] : []),
            preferStdin ? "-" : prompt,
          ],
          env: extraEnv,
          stdin: preferStdin ? prompt : undefined,
        };
        break;
      }
      default:
        throw new Error(`Provider "${p}" does not support CLI mode.`);
    }
    return this.wrapWithOsSandbox(base, p);
  }

  /**
   * Device-local cache base for plugin CLI byproducts (codex output, generated MCP
   * config, temp images). Lives in the project's gitignored `.cache/` — matching the
   * backend's `<repo>/.cache/vision_render` — NOT under `~/` or the OS temp dir.
   */
  private cliCacheBase(): string {
    const configured = expandPath((this.settings.incuratorRepoPath || "").trim());
    if (configured) return join(configured, ".cache", "cli");
    throw new Error("Incurator CLI cache requires incuratorRepoPath.");
  }

  private cliTempDir(): string {
    const dir = join(this.cliCacheBase(), "tmp");
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    return dir;
  }

  /**
   * Remove a per-call chat image run dir (v0.28.0). Best-effort; called in the
   * CLI/stream finally on success, error, AND abort so no temp image survives a
   * completed send. See PLUGIN_SCHEMA §2.1.3.
   */
  private cleanupChatImageDir(dir: string | null): void {
    if (!dir) return;
    try {
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort: a missing dir or racing cleanup is fine */
    }
  }

  /**
   * Sweep crash-leftover chat image dirs on startup (v0.28.0). Uses cliCacheBase()
   * (no mkdir side effect); `force` makes a missing dir a no-op.
   */
  private sweepStaleChatImages(): void {
    try {
      rmSync(join(this.cliCacheBase(), "chat_images"), { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  }

  private _cliCwdCreated: string | null = null;
  private _cliCwdResolved = "";
  private getCliCwd(): string {
    const dir = this.cliCacheBase();
    if (this._cliCwdCreated !== dir) {
      // Only stat/mkdir when the resolved path changes (settings edit), not every call.
      if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
      // Return the REAL path: macOS firmlinks /var→/private/var and a repo may sit
      // under a symlink, so the cwd/output-file/sandbox-rule all need the canonical
      // form to agree (otherwise Seatbelt's subpath rule won't match the write).
      try { this._cliCwdResolved = realpathSync(dir); } catch { this._cliCwdResolved = dir; }
      this._cliCwdCreated = dir;
    }
    return this._cliCwdResolved;
  }

  // --- CLI tool-scope sandbox (v0.23.0; SYSTEM_BEHAVIOR §… popover tool scope) ---

  /** Realpath-resolve + dedupe a set of path candidates, dropping empties. */
  private resolveRoots(candidates: string[]): string[] {
    const out: string[] = [];
    for (const raw of candidates) {
      const p = expandPath((raw || "").trim());
      if (!p) continue; // SECURITY: drop empty/undefined BEFORE use (never --add-dir "")
      try {
        out.push(realpathSync(p));
      } catch {
        out.push(p); // path may not exist yet; pass the literal (still scoped)
      }
    }
    return Array.from(new Set(out));
  }

  /**
   * Roots the CLI tools may READ/reference (vault + Zotero library + its `storage/`),
   * surfaced to the agent via `--add-dir`. Reads are allowed broadly by the OS sandbox
   * regardless; this is the visibility set, NOT the writable set.
   */
  private allowedRoots(): string[] {
    const z = (this.settings.zoteroBasePath || "").trim();
    return this.resolveRoots([
      this.vaultRoot,
      z,
      z ? join(expandPath(z), "storage") : "",
    ]);
  }

  /**
   * Roots the sandboxed CLI may WRITE to: the vault (the agent's editable knowledge
   * space) only. The Zotero library is an EXTERNAL read-only reference — granting it
   * write would let a prompt-injected agent corrupt/delete the user's research data,
   * and it's unnecessary (the agent only reads PDFs). `getCliCwd()` is added by the
   * caller for the CLI's own operational files.
   */
  private sandboxWriteRoots(): string[] {
    return this.resolveRoots([this.vaultRoot]);
  }

  private _bwrapPath: string | null | undefined;
  /** In-process PATH lookup for `bwrap` — no subprocess (never blocks the UI). */
  private resolveBwrap(): string {
    if (this._bwrapPath !== undefined) return this._bwrapPath || "";
    this._bwrapPath = null;
    for (const dir of (process.env.PATH || "").split(":")) {
      if (!dir) continue;
      const candidate = join(dir, "bwrap");
      if (existsSync(candidate)) {
        this._bwrapPath = candidate;
        break;
      }
    }
    return this._bwrapPath || "";
  }

  /**
   * OS-sandbox the CLI command. agy MUST be contained this way (its own --sandbox is
   * ineffective); claude/codex use it as defense-in-depth on top of their flags. The
   * macOS profile is passed INLINE via `sandbox-exec -p` (no temp file → no
   * multi-vault / concurrent-call collision). Returns the wrapped command, or refuses
   * (throws) when agy can't be sandboxed.
   */
  private wrapWithOsSandbox(
    base: { command: string; args: string[]; env?: Record<string, string>; stdin?: string },
    provider: LLMProvider,
  ): { command: string; args: string[]; env?: Record<string, string>; stdin?: string } {
    // macOS firmlinks `/var`→`/private/var`, so a Seatbelt `(subpath ...)` only matches
    // the REAL resolved path. getCliCwd() and sandboxWriteRoots() already return
    // realpath'd paths; home and the CLI temp dir are resolved here too.
    const realOr = (p: string): string => {
      try { return realpathSync(p); } catch { return p; }
    };
    // Writable set = the vault + the CLI's own operational dir (logs/output files).
    // Zotero is deliberately NOT here (read-only reference; reads are allowed anyway).
    const roots = [...this.sandboxWriteRoots(), this.getCliCwd()];
    const plan = buildSandboxPlan({
      platform: process.platform,
      allowedRoots: roots,
      home: realOr(homedir()),
      tmpdir: realOr(this.cliTempDir()),
      sandboxExecPath: process.platform === "darwin" ? "/usr/bin/sandbox-exec" : "",
      bwrapPath: process.platform === "linux" ? this.resolveBwrap() : "",
      provider,
    });

    if (plan.unavailable) {
      // agy's own --sandbox is INEFFECTIVE (P0), so without the OS sandbox it has no
      // containment → refuse. claude/codex DO self-contain via their flags (claude's
      // tool denylist / codex's workspace-write), so they degrade to that weaker
      // flag-based posture rather than being refused — but warn so the drop is visible.
      if (provider === "antigravity") {
        throw new Error(
          `Antigravity (agy) cannot be safely sandboxed here, so it is blocked from tool ` +
          `use. ${plan.reason ?? ""} Switch the provider to Claude/Codex/Ollama, or install ` +
          `the sandbox tool.`
        );
      }
      logger.warn(
        `OS sandbox unavailable (${plan.reason ?? process.platform}); ` +
        `${provider} runs under its own flag-based containment only (weaker posture).`
      );
      return base;
    }
    return {
      command: plan.prefix[0],
      args: [...plan.prefix.slice(1), base.command, ...base.args],
      env: base.env,
      stdin: base.stdin,
    };
  }

  private processMcpServer(server: any): any {
    const replaceVars = (str: string) => str.replace(/\{VAULT_ROOT\}/g, this.vaultRoot);
    
    const processedEnv: Record<string, string> = {};
    for (const [k, v] of Object.entries(server.env || {})) {
      processedEnv[k] = typeof v === 'string' ? replaceVars(v) : String(v);
    }

    return {
      command: server.command,
      args: (server.args || []).map((a: string) => replaceVars(a)),
      env: processedEnv,
    };
  }

  private syncClaudeMcpConfig(): string {
    const mcpServers: Record<string, unknown> = {};
    for (const server of this.settings.mcpServers) {
      if (server.enabled) {
        mcpServers[server.name] = this.processMcpServer(server);
      }
    }
    const claudeMcpPath = join(this.getCliCwd(), "claude_mcp.json");
    writeFileSync(
      claudeMcpPath,
      JSON.stringify({ mcpServers }, null, 2)
    );
    return claudeMcpPath;
  }

  private syncCodexMcpConfig(): void {
    const codexDir = join(homedir(), ".codex");
    if (!existsSync(codexDir)) {
      mkdirSync(codexDir, { recursive: true });
    }
    const tomlPath = join(codexDir, "obsidian.config.toml");
    
    let tomlContent = "";
    for (const rawServer of this.settings.mcpServers) {
      if (!rawServer.enabled) continue;
      const server = this.processMcpServer(rawServer);
      tomlContent += `[mcp_servers.${rawServer.name}]\n`;
      tomlContent += `command = ${JSON.stringify(server.command)}\n`;
      tomlContent += `args = ${JSON.stringify(server.args)}\n`;
      if (server.env && Object.keys(server.env).length > 0) {
        tomlContent += `[mcp_servers.${rawServer.name}.env]\n`;
        for (const [k, v] of Object.entries(server.env)) {
          tomlContent += `${k} = ${JSON.stringify(v)}\n`;
        }
      }
      tomlContent += "\n";
    }
    writeFileSync(tomlPath, tomlContent);
  }

  private syncAgyMcpConfig(): void {
    const geminiDir = join(homedir(), ".gemini");
    mkdirSync(geminiDir, { recursive: true });

    const mcpServers: Record<string, unknown> = {};
    for (const server of this.settings.mcpServers) {
      if (server.enabled) {
        mcpServers[server.name] = this.processMcpServer(server);
      }
    }

    const settingsPath = join(geminiDir, "settings.json");
    let existing: Record<string, unknown> = {};
    try {
      existing = JSON.parse(readFileSync(settingsPath, "utf-8"));
    } catch { /* file missing or malformed — start fresh */ }

    const merged = {
      ...existing,
      admin: {
        ...(existing.admin as Record<string, unknown> | undefined ?? {}),
        mcp: { enabled: true },
      },
      mcpServers,
    };

    writeFileSync(settingsPath, `${JSON.stringify(merged, null, 2)}\n`);
    syncAgyHeadlessReadPermission(geminiDir);
  }

  private messagesToCliPrompt(messages: LLMMessage[]): string {
    // Reset per-call image state; contentToCliText (below) lazily fills these as
    // it writes image parts to the scoped chat_images dir for this invocation.
    this._chatImageRunDir = null;
    this._chatImagePaths = [];
    return messages
      .map((message) => {
        const content = this.contentToCliText(message.content);
        const label =
          message.role === "system"
            ? "System"
            : message.role === "assistant"
              ? "Assistant"
              : "User";
        return `${label}:\n${content}`;
      })
      .join("\n\n---\n\n")
      // PDF text extraction can embed null bytes (\0) which are valid in JS
      // strings but fatal in C-strings passed to OS execve via spawn().
      // Strip them here — the single funnel for all CLI prompts.
      .replace(/\0/g, "");
  }

  private contentToCliText(content: string | LLMContentPart[]): string {
    if (typeof content === "string") return content;
    return content
      .map((part) => {
        if (part.type === "text") return part.text;
        
        try {
          // v0.28.0: write each image to a per-call chat_images run dir under the
          // (OS-sandbox-covered) CLI cwd and reference it by path, so a vision CLI
          // reads it directly. buildCliCommand scopes Read for image-bearing turns.
          if (!this._chatImageRunDir) {
            this._chatImageRunDir = join(
              this.getCliCwd(),
              "chat_images",
              `${Date.now()}-${Math.random().toString(36).slice(2)}`
            );
            mkdirSync(this._chatImageRunDir, { recursive: true });
          }
          let ext = part.mimeType.split("/")[1] || "png";
          if (ext === "jpeg") ext = "jpg";
          const filepath = join(this._chatImageRunDir, `img_${this._chatImagePaths.length}.${ext}`);
          writeFileSync(filepath, Buffer.from(part.data, "base64"));
          this._chatImagePaths.push(filepath);
          // Mirror the backend describe_image_via_cli phrasing so the vision CLI
          // opens the file (scoped Read enabled for image turns in buildCliCommand).
          return `Read the image file at ${filepath} to see the attached image/crop, then use it to answer.`;
        } catch (e) {
          return `[Attached image ${part.mimeType} omitted from CLI fallback (save failed: ${e instanceof Error ? e.message : String(e)})]`;
        }
      })
      .join("\n");
  }

  private cleanCliOutput(provider: LLMProvider, stdout: string): string {
    const trimmed = stdout.trim();
    if (provider !== "openai") return trimmed;

    const lines = trimmed
      .split(/\r?\n/)
      .filter((line) => {
        const value = line.trim();
        return (
          value.length > 0 &&
          value !== "codex" &&
          value !== "tokens used" &&
          !/^[\d,]+$/.test(value) &&
          !value.startsWith("202")
        );
      });

    return lines.join("\n").trim();
  }

  /**
   * Edit text using the LLM — returns only the modified text.
   */
  async editText(
    originalText: string,
    instruction: string,
    onChunk?: (chunk: StreamChunk) => void
  ): Promise<string> {
    const messages: LLMMessage[] = [
      {
        role: "system",
        content: `You are an expert text editor embedded in Obsidian. The user will give you a piece of text and an editing instruction.

RULES:
- Apply the instruction to the text and return ONLY the modified text.
- Do NOT include any explanation, preamble, or markdown code fences.
- Preserve the original formatting (markdown, indentation) unless the instruction says otherwise.
- If the instruction is unclear, make your best judgment.`,
      },
      {
        role: "user",
        content: `Original text:
\`\`\`
${originalText}
\`\`\`

Instruction: ${instruction}`,
      },
    ];

    if (onChunk && this.settings.streamingEnabled) {
      return this.streamChat(messages, onChunk);
    }
    return this.complete(messages);
  }
}
