"""Raw ingest: parse source files, register in the state DB, generate L1 Contexts.

This module handles the `wiki add` phase:
  1. Discover files in raw_dirs (02_Wiki, 03_Notes, 04_Resources, 06_Archives)
  2. Register each file in the `sources` table with a content hash
  3. Generate L1 Contexts (summary + atom candidates).

L2 Atoms and L3 Concepts are generated by ingest_llm.run_l1_to_l3().
L4 Exhibitions are generated by ingest_llm.run_l4_scoped() (wiki curate).
"""

from __future__ import annotations
from . import constants as consts

import json
import re
import shutil
import uuid
import hashlib
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from pydantic import BaseModel, Field
from typing import Iterable

from . import config as cfg
from . import constants as consts
from . import db
from . import parsers
from .llm import LLMError


class AddResult(str, Enum):
    ADDED = "added"
    DEDUPED = "deduped"
    SKIPPED_EMPTY = "skipped_empty"
    SKIPPED_UNSUPPORTED = "skipped_unsupported"
    ERROR = "error"


@dataclass
class AddOutcome:
    """Result of attempting to add a single file."""

    result: AddResult
    source_path: Path              # Where the file ended up (or original on error)
    relpath: str                   # Relative to project root
    title: str | None = None
    file_type: str | None = None
    bytes: int = 0
    word_count: int = 0
    content_hash: str | None = None
    source_id: int | None = None   # Row ID in sources table
    context_id: str | None = None  # CTX-UUID for L1 context page
    message: str = ""              # Human-friendly explanation

    @property
    def ok(self) -> bool:
        return self.result == AddResult.ADDED

    @property
    def is_warning(self) -> bool:
        return self.result in {
            AddResult.DEDUPED,
            AddResult.SKIPPED_EMPTY,
            AddResult.SKIPPED_UNSUPPORTED,
        }


@dataclass
class ImportPlan:
    """Resolved destination for a source import."""

    source_path: Path
    destination_path: Path
    relpath: str
    policy: str
    copied: bool


def _default_logical_source_id(source: Path) -> str:
    """Create a deterministic logical id from the source path.

    This is a v1 fallback. Dedicated integrations such as Zotero should replace
    it with the external system's stable item key when available.
    """
    digest = hashlib.sha256(str(source.expanduser().resolve()).encode("utf-8")).hexdigest()
    return f"ref-{digest[:16]}"


import os

def _resolve_reference_source(paths: cfg.WikiPaths, source: Path) -> Path:
    """Resolve Reference Mode Markdown Stubs to their actual external target.
    
    If the file is a markdown stub with `type: reference` frontmatter, returns the
    resolved absolute path of the external file (e.g. from Zotero). Otherwise returns
    the original source unmodified.
    """
    if source.suffix.lower() != ".md":
        return source
    
    try:
        content = source.read_text(encoding="utf-8")
        if not content.startswith("---"):
            return source
            
        end_idx = content.find("---", 3)
        if end_idx == -1:
            return source
            
        import yaml
        fm = yaml.safe_load(content[3:end_idx])
        if not isinstance(fm, dict) or fm.get("type") != "reference":
            return source
            
        target_path = None
        if fm.get("zotero_key"):
            from . import zotero
            # Check config or env for zotero roots
            zotero_roots = []
            config = cfg.load_config(paths)
            if "external" in config and "zotero" in config["external"]:
                zotero_roots = config["external"]["zotero"].get("roots", [])
            
            env_zotero = os.environ.get("ZOTERO_BASE_PATH")
            if env_zotero:
                zotero_roots.insert(0, env_zotero)
                
            for z_root in zotero_roots:
                resolved = zotero.resolve_zotero_attachment_path(z_root, fm["zotero_key"])
                if resolved:
                    target_path = resolved
                    break
        
        if not target_path and fm.get("target_path"):
            target_path = fm["target_path"]
            
        if target_path:
            target_p = Path(target_path)
            if target_p.exists():
                return target_p
    except Exception:
        pass
        
    return source


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _today_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _generate_id(prefix: str) -> str:
    """Generate a prefixed UUID4, e.g. 'CTX-a1b2c3d4'."""
    return f"{prefix}-{uuid.uuid4().hex[:8]}"


def _is_inside_raw(path: Path, raw_dirs: list[Path]) -> bool:
    """True if `path` is already inside one of the project's raw directories."""
    path = path.resolve()
    for d in raw_dirs:
        try:
            path.relative_to(d.resolve())
            return True
        except ValueError:
            pass
    return False


def _is_inside(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def _safe_relative_path(path: Path) -> Path:
    if path.is_absolute():
        raise ValueError("Destination must be vault-relative, not absolute.")
    parts = []
    for part in path.parts:
        if part in ("", "."):
            continue
        if part == "..":
            raise ValueError("Destination may not contain '..'.")
        parts.append(part)
    if not parts:
        raise ValueError("Destination path is empty.")
    return Path(*parts)


def _unique_destination(path: Path) -> Path:
    if not path.exists():
        return path
    stem = path.stem
    suffix = path.suffix
    parent = path.parent
    for idx in range(2, 10_000):
        candidate = parent / f"{stem}-{idx}{suffix}"
        if not candidate.exists():
            return candidate
    raise FileExistsError(f"Could not find a free destination near {path}")


def safe_import_destination(
    paths: cfg.WikiPaths,
    source: Path,
    *,
    policy: str = "mirror_03_to_04",
    destination: str | Path | None = None,
) -> ImportPlan:
    """Resolve a safe destination for importing a source into the vault.

    `mirror_03_to_04` keeps direct imports out of human-authored 03_Notes by
    mirroring those paths under 04_Resources. Other external files land under
    04_Resources/Imports. Files already inside an allowed raw directory are
    reused in place unless the mirror policy maps 03_Notes to 04_Resources.
    """
    if policy == "copy":
        policy = "into_04_resources"
    if policy not in {"mirror_03_to_04", "into_04_resources"}:
        raise ValueError(f"Unsupported import policy: {policy}")

    source = source.expanduser().resolve()
    if not source.exists() or not source.is_file():
        raise FileNotFoundError(f"File not found: {source}")
    if not parsers.is_supported(source):
        raise ValueError(f"Unsupported file type: {source.suffix or '(no extension)'}")

    root = paths.root.resolve()
    resources_dir = root / consts.DIR_RESOURCES
    notes_dir = root / consts.DIR_NOTES
    collections_dir = paths.collections.resolve()

    if _is_inside(source, collections_dir):
        raise ValueError("Refusing to import from .curator/Collections.")

    if destination is not None:
        rel_dest = _safe_relative_path(Path(destination))
        dest = root / rel_dest
        if dest.suffix == "":
            dest = dest / source.name
    elif policy == "mirror_03_to_04" and _is_inside(source, notes_dir):
        dest = resources_dir / source.relative_to(notes_dir)
    elif _is_inside_raw(source, paths.raw_dirs):
        return ImportPlan(
            source_path=source,
            destination_path=source,
            relpath=str(source.relative_to(root)) if _is_inside(source, root) else str(source),
            policy=policy,
            copied=False,
        )
    else:
        dest = resources_dir / "Imports" / source.name

    dest = dest.resolve()
    if not _is_inside(dest, resources_dir):
        raise ValueError("Import destination must stay inside 04_Resources.")
    if _is_inside(dest, collections_dir):
        raise ValueError("Import destination may not be inside .curator/Collections.")

    try:
        if source.samefile(dest):
            return ImportPlan(
                source_path=source,
                destination_path=source,
                relpath=str(source.relative_to(root)) if _is_inside(source, root) else str(source),
                policy=policy,
                copied=False,
            )
    except OSError:
        pass

    dest = _unique_destination(dest)
    return ImportPlan(
        source_path=source,
        destination_path=dest,
        relpath=str(dest.relative_to(root)),
        policy=policy,
        copied=True,
    )


def _record_pdf_pages_for_parsed(
    paths: cfg.WikiPaths,
    source_id: int | None,
    relpath: str,
    parsed,
) -> None:
    if source_id is None or parsed.file_type != "pdf":
        return
    pages = parsed.metadata.get("pdf_pages") or []
    if isinstance(pages, list):
        db.replace_source_pdf_pages(paths.state_db, source_id, relpath, pages)


def _record_pdf_pages_conn(conn, source_id: int | None, relpath: str, parsed) -> None:
    if source_id is None or parsed.file_type != "pdf":
        return
    pages = parsed.metadata.get("pdf_pages") or []
    if not isinstance(pages, list):
        return
    now = _now_iso()
    conn.execute("DELETE FROM source_pdf_pages WHERE source_id = ?", (source_id,))
    for page in pages:
        page_number = int(page.get("page") or page.get("page_number") or 0)
        if page_number <= 0:
            continue
        metadata = {
            k: v
            for k, v in page.items()
            if k
            not in {"page", "page_number", "content_hash", "char_count", "word_count", "text"}
        }
        conn.execute(
            """
            INSERT INTO source_pdf_pages
                (source_id, relpath, page_number, content_hash, char_count,
                 word_count, metadata, extracted_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                source_id,
                relpath,
                page_number,
                str(page.get("content_hash") or ""),
                int(page.get("char_count") or 0),
                int(page.get("word_count") or 0),
                json.dumps(metadata, ensure_ascii=False, sort_keys=True),
                now,
            ),
        )


# ---------------------------------------------------------------------------
# L1 Summary generation (Pass 0)
# ---------------------------------------------------------------------------


MAX_SUMMARY_CHARS = 35_000  # ~8.5K tokens
MAX_IMAGES_PER_DOC = 5     # cap vision calls per document


def _resolve_image_link(raw_link: str, source_file: Path, vault_root: Path) -> Path | None:
    """Resolve a raw image link string to an absolute path.

    Tries vault-root-relative first (Obsidian style: "05_Assets/foo.png"),
    then source-file-relative (standard Markdown: "../images/foo.png").
    """
    candidate = vault_root / raw_link
    if candidate.exists():
        return candidate
    candidate = source_file.parent / raw_link
    if candidate.exists():
        return candidate
    return None


def _describe_images_with_vision(
    client,
    images: list[bytes],
    context: str,
) -> list[str]:
    """Describe a list of images using the client's vision capability.

    Returns a list of description strings (one per image). Skips silently on
    failure so the overall ingest is not aborted by a bad image.
    """
    from . import prompts

    descriptions: list[str] = []
    msgs = prompts.build_image_description_messages(context=context)
    vision_prompt = msgs[-1].content  # the user turn text

    for img_data in images:
        try:
            desc = client.describe_image(img_data, prompt=vision_prompt)
            if desc:
                descriptions.append(desc)
        except Exception as e:
            print(f"    [Warn] Vision inference failed: {e}")
    return descriptions


def _extract_json_object(text: str) -> str:
    """Find the first top-level {...} block in text."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.split("\n", 1)
        if len(lines) == 2:
            text = lines[1]
        if text.rstrip().endswith("```"):
            text = text.rsplit("```", 1)[0]
    start = text.find("{")
    if start == -1:
        return text
    depth = 0
    in_string = False
    escape = False
    for i in range(start, len(text)):
        c = text[i]
        if escape:
            escape = False
            continue
        if c == "\\":
            escape = True
            continue
        if c == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    return text[start:]


def _loads_json_relaxed(json_str: str) -> dict:
    """Load LLM JSON, repairing common LaTeX backslashes inside strings."""
    def _repair_string_escapes(match: re.Match[str]) -> str:
        content = match.group(0)[1:-1]
        repaired: list[str] = []
        i = 0
        while i < len(content):
            char = content[i]
            if char != "\\":
                repaired.append(char)
                i += 1
                continue

            if i + 1 >= len(content):
                repaired.append("\\\\")
                i += 1
                continue

            nxt = content[i + 1]
            if nxt in '"\\/bfnrt':
                repaired.append("\\" + nxt)
                i += 2
                continue

            if (
                nxt == "u"
                and i + 5 < len(content)
                and all(c in "0123456789abcdefABCDEF" for c in content[i + 2:i + 6])
            ):
                repaired.append("\\" + content[i + 1:i + 6])
                i += 6
                continue

            repaired.append("\\\\")
            i += 1

        return '"' + "".join(repaired) + '"'

    try:
        return json.loads(json_str, strict=False)
    except json.JSONDecodeError as original_error:
        repaired = re.sub(r'"([^"\\]|\\.)*"', _repair_string_escapes, json_str)
        try:
            return json.loads(repaired, strict=False)
        except json.JSONDecodeError:
            raise original_error


def _chunk_text(text: str, chunk_size: int = 30000, overlap: int = 2500) -> list[str]:
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])
        if end >= len(text):
            break
        start += chunk_size - overlap
    return chunks


def _parse_summary_json(raw_response: str) -> dict:
    return _loads_json_relaxed(_extract_json_object(raw_response))


def _summarize_chunk_with_fallback(
    client,
    prompts_module,
    *,
    title: str,
    chunk: str,
    label: str,
    depth: int = 0,
) -> tuple[list[dict], Exception | None]:
    messages = prompts_module.build_summary_messages(title, chunk)
    last_error: Exception | None = None

    try:
        raw_response = client.chat(
            messages,
            json_mode=True,
            temperature=0.2,
        )
        try:
            return [_parse_summary_json(raw_response)], None
        except json.JSONDecodeError as e:
            last_error = e
            retry_messages = prompts_module.build_summary_retry_messages(
                title, chunk, raw_response
            )
            raw_response = client.chat(
                retry_messages,
                json_mode=True,
                temperature=0.1,
            )
            return [_parse_summary_json(raw_response)], None
    except (json.JSONDecodeError, LLMError) as e:
        last_error = e

    if depth < 2 and len(chunk) > 9000:
        sub_size = max(6000, len(chunk) // 2)
        overlap = min(1000, max(250, sub_size // 10))
        subchunks = _chunk_text(chunk, chunk_size=sub_size, overlap=overlap)
        if len(subchunks) > 1:
            print(
                f"    -> {label} failed ({last_error}); retrying as "
                f"{len(subchunks)} smaller chunk(s)."
            )
            data: list[dict] = []
            for sub_idx, subchunk in enumerate(subchunks, 1):
                sub_label = f"{label}.{sub_idx}"
                sub_data, sub_error = _summarize_chunk_with_fallback(
                    client,
                    prompts_module,
                    title=title,
                    chunk=subchunk,
                    label=sub_label,
                    depth=depth + 1,
                )
                if sub_error:
                    return [], sub_error
                data.extend(sub_data)
            return data, None

    return [], last_error


def _normalize_atom_name(name: str) -> str:
    clean = re.sub(r"\([^)]*\)", "", name.lower())
    clean = re.sub(r"[^a-z0-9가-힣]+", " ", clean)
    return re.sub(r"\s+", " ", clean).strip()


def _dedupe_atom_candidates(candidates: list[dict]) -> list[dict]:
    seen: set[str] = set()
    unique: list[dict] = []
    for candidate in candidates:
        if not isinstance(candidate, dict):
            continue
        name = str(candidate.get("name", "")).strip()
        if not name:
            continue
        key = _normalize_atom_name(name) or name.lower()
        if key in seen:
            continue
        seen.add(key)
        unique.append(
            {
                "name": name,
                "type": str(candidate.get("type", consts.CLAIM_TYPE_FACT) or consts.CLAIM_TYPE_FACT).strip() or consts.CLAIM_TYPE_FACT,
                "one_liner": str(candidate.get("one_liner", "") or "").strip(),
            }
        )
    return unique


def _prepare_atom_candidates(candidates: list[dict]) -> list[dict]:
    """Keep L1 Atom Candidates granular; only remove exact duplicates.

    Cross-source equivalence is discovered during sync at L3/L4, where the
    system has enough context to decide whether different terms share logic.
    L1 should preserve recall instead of compressing candidates early.
    """
    return _dedupe_atom_candidates(candidates)


def _section_id(index: int) -> str:
    return f"s{index}"


def _clean_section_title(title: str, fallback: str) -> str:
    title = re.sub(r"\s+", " ", title or "").strip()
    return title[:120] or fallback


def _extract_markdown_sections(text: str, *, default_title: str) -> list[dict]:
    """Split text into structural sections without using an LLM."""
    matches = list(re.finditer(r"(?m)^(#{1,6})\s+(.+?)\s*$", text or ""))
    if not matches:
        return [
            {
                "id": _section_id(1),
                "level": 2,
                "title": _clean_section_title(default_title, "Document"),
                "page": 1,
                "text": (text or "").strip(),
            }
        ]

    sections: list[dict] = []
    for idx, match in enumerate(matches, 1):
        next_start = matches[idx].start() if idx < len(matches) else len(text)
        heading = _clean_section_title(match.group(2), f"Section {idx}")
        body = text[match.end() : next_start].strip()
        sections.append(
            {
                "id": _section_id(idx),
                "level": min(len(match.group(1)), 6),
                "title": heading,
                "page": 1,
                "text": body,
            }
        )
    return sections


# Patterns that identify heading-like lines in raw PDF text
_NUMBERED_HEADING = re.compile(
    r"^(\d+\.)+\s+[A-Z]",          # "1. Introduction", "2.1 Methods"
)
_ALLCAPS_HEADING = re.compile(
    r"^[A-Z][A-Z\s\-/]{2,49}$",    # "INTRODUCTION", "METHODS AND RESULTS"
)
_KNOWN_SECTION_NAMES = frozenset({
    "abstract", "introduction", "background", "related work",
    "motivation", "methodology", "methods", "method", "approach",
    "experiment", "experiments", "evaluation", "results",
    "discussion", "conclusion", "conclusions", "future work",
    "acknowledgment", "acknowledgments", "acknowledgements",
    "references", "bibliography", "appendix",
})


def _looks_like_heading(line: str) -> tuple[bool, int]:
    """Return (is_heading, level). Level 1 for top-level, 2 for sub."""
    stripped = line.strip()
    if not stripped or len(stripped) > 80:
        return False, 0
    if _NUMBERED_HEADING.match(stripped):
        depth = stripped.split()[0].count(".")
        return True, max(1, depth)
    if _ALLCAPS_HEADING.match(stripped) and not stripped[0].isdigit():
        return True, 1
    lower = stripped.lower().rstrip(".:")
    if lower in _KNOWN_SECTION_NAMES and len(stripped) <= 40:
        return True, 1
    return False, 0


def _infer_sections_from_layout(pages: list[dict]) -> list[dict]:
    """Detect heading-like lines across page text and group content into sections.

    Returns [] if fewer than 2 headings are found (caller falls back to page-by-page).
    """
    # Collect (page_no, line_idx, heading_text, level) for each detected heading
    heading_anchors: list[tuple[int, int, str, int]] = []
    for page in pages:
        page_no = int(page.get("page") or page.get("page_number") or 0)
        if not page_no:
            continue
        text = str(page.get("text") or "")
        lines = text.splitlines()
        for li, line in enumerate(lines):
            is_h, level = _looks_like_heading(line)
            if is_h:
                heading_anchors.append((page_no, li, line.strip(), level))

    if len(heading_anchors) < 2:
        return []

    # Build sections: each heading spans from its page to the next heading's page
    page_text_by_no = {
        int(p.get("page") or p.get("page_number") or 0): str(p.get("text") or "").strip()
        for p in pages
        if int(p.get("page") or p.get("page_number") or 0) > 0
    }
    sorted_page_nos = sorted(page_text_by_no)

    sections: list[dict] = []
    for anchor_idx, (start_page, _li, heading, level) in enumerate(heading_anchors):
        next_start = heading_anchors[anchor_idx + 1][0] if anchor_idx + 1 < len(heading_anchors) else None
        section_pages = [
            pn for pn in sorted_page_nos
            if pn >= start_page and (next_start is None or pn < next_start)
        ]
        text = "\n\n".join(page_text_by_no[pn] for pn in section_pages).strip()
        sections.append({
            "id": _section_id(len(sections) + 1),
            "level": level,
            "title": _clean_section_title(heading, f"Section {len(sections) + 1}"),
            "page": start_page,
            "text": text,
        })

    return sections


def _extract_pdf_sections(parsed) -> list[dict]:
    pages = parsed.metadata.get("pdf_pages") or []
    toc = parsed.metadata.get("pdf_toc") or []
    if isinstance(pages, list) and isinstance(toc, list) and toc:
        page_text_by_number = {
            int(p.get("page") or p.get("page_number") or 0): str(p.get("text") or "").strip()
            for p in pages
            if int(p.get("page") or p.get("page_number") or 0) > 0
        }
        sorted_pages = sorted(page_text_by_number)
        sections: list[dict] = []
        for idx, item in enumerate(toc, 1):
            try:
                level = int(item.get("level") or 1)
                start_page = int(item.get("page") or 1)
            except (AttributeError, TypeError, ValueError):
                continue
            next_page = None
            for next_item in toc[idx:]:
                try:
                    candidate_page = int(next_item.get("page") or 0)
                except (AttributeError, TypeError, ValueError):
                    continue
                if candidate_page > start_page:
                    next_page = candidate_page
                    break
            section_pages = [
                page_no
                for page_no in sorted_pages
                if page_no >= start_page and (next_page is None or page_no < next_page)
            ]
            text = "\n\n".join(page_text_by_number[p] for p in section_pages).strip()
            sections.append(
                {
                    "id": _section_id(len(sections) + 1),
                    "level": max(1, min(level, 6)),
                    "title": _clean_section_title(str(item.get("title") or ""), f"Section {idx}"),
                    "page": start_page,
                    "text": text,
                }
            )
        if sections:
            return sections

    if isinstance(pages, list) and pages:
        # Try to infer logical sections from text layout before falling back to page-by-page.
        inferred = _infer_sections_from_layout(pages)
        if inferred:
            return inferred

        # Page-by-page fallback when no layout headings detected
        sections = []
        for page in pages:
            page_no = int(page.get("page") or page.get("page_number") or len(sections) + 1)
            text = str(page.get("text") or "").strip()
            if not text:
                continue
            sections.append(
                {
                    "id": _section_id(len(sections) + 1),
                    "level": 2,
                    "title": f"Page {page_no}",
                    "page": page_no,
                    "text": text,
                }
            )
        if sections:
            return sections

    return _extract_markdown_sections(parsed.text, default_title=parsed.title)


def _extract_structural_sections(parsed) -> list[dict]:
    if parsed.file_type == "pdf":
        return _extract_pdf_sections(parsed)
    return _extract_markdown_sections(parsed.text, default_title=parsed.title)


def _structural_atom_candidates(sections: list[dict], title: str) -> list[dict]:
    candidates: list[dict] = []
    for section in sections[:24]:
        section_title = _clean_section_title(str(section.get("title") or ""), title)
        page = int(section.get("page") or 1)
        candidates.append(
            {
                "name": section_title,
                "type": consts.CLAIM_TYPE_FACT,
                "one_liner": (
                    "Extract the atomic claims, methods, entities, and constraints "
                    f"from section '{section_title}' starting on page {page}."
                ),
            }
        )
    if candidates:
        return candidates
    return [
        {
            "name": _clean_section_title(title, "Document"),
            "type": consts.CLAIM_TYPE_FACT,
            "one_liner": "Extract the atomic claims, methods, entities, and constraints from this source.",
        }
    ]


def _save_pdf_images(parsed, relpath: str, paths: cfg.WikiPaths) -> list[dict]:
    """Save embedded PDF images to 05_Assets/<slug>/ and return obsidian metadata.

    Images smaller than 1 KB are skipped (icons, decorators).
    Returns [] when parsed is not a PDF or has no images. Silently ignores errors.
    """
    if parsed.file_type != "pdf":
        return []
    pdf_images: list[dict] = parsed.metadata.get("pdf_images", [])
    if not pdf_images:
        return []

    slug = re.sub(r"[^\w\-]", "_", Path(relpath).stem)[:40].strip("_") or "source"
    assets_dir = paths.root / consts.DIR_ASSETS / slug
    saved: list[dict] = []
    try:
        assets_dir.mkdir(parents=True, exist_ok=True)
        idx_per_page: dict[int, int] = {}
        for img in pdf_images:
            page = int(img.get("page", 1))
            idx_per_page[page] = idx_per_page.get(page, 0) + 1
            idx = idx_per_page[page]
            ext = str(img.get("ext", "png"))
            filename = f"p{page:02d}_img{idx:02d}.{ext}"
            dest = assets_dir / filename
            dest.write_bytes(img["data"])
            saved.append({"obsidian_path": f"{consts.DIR_ASSETS}/{slug}/{filename}", "page": page})
    except Exception:
        pass
    return saved


def _build_structural_context_page(
    *,
    context_id: str,
    parsed,
    relpath: str,
    content_hash: str,
    today: str,
    saved_images: list[dict] | None = None,
) -> str:
    import yaml

    sections = _extract_structural_sections(parsed)
    candidates = _structural_atom_candidates(sections, parsed.title)
    compact_pages: list[dict] = []
    pdf_pages = parsed.metadata.get("pdf_pages") or []
    if parsed.file_type == "pdf" and isinstance(pdf_pages, list):
        compact_pages = [
            {
                "page": int(p.get("page") or 0),
                "hash": str(p.get("content_hash") or "")[:16],
                "chars": int(p.get("char_count") or 0),
                "words": int(p.get("word_count") or 0),
            }
            for p in pdf_pages
            if int(p.get("page") or 0) > 0
        ]

    frontmatter: dict = {
        "id": context_id,
        "type": consts.TYPE_L1,
        "source_path": f"[[{relpath.removesuffix('.md')}]]",
        "source_hash": content_hash,
        "content_hash": hashlib.sha256((parsed.text or "").encode("utf-8")).hexdigest()[:16],
        "domain": consts.DOMAIN_GENERAL,
        "last_updated": today,
        "tags": [parsed.file_type, "instant-l1"],
        "toc": [
            {
                "id": str(section.get("id") or _section_id(idx)),
                "level": int(section.get("level") or 2),
                "title": str(section.get("title") or f"Section {idx}"),
                "page": int(section.get("page") or 1),
            }
            for idx, section in enumerate(sections, 1)
        ],
    }
    if compact_pages:
        frontmatter["source_page_count"] = len(compact_pages)
        frontmatter["source_pages"] = compact_pages
    if saved_images:
        frontmatter["embedded_images"] = [
            {"obsidian_path": img["obsidian_path"], "page": img["page"]}
            for img in saved_images
        ]

    key_claims_text = "- Pending L2 extraction from structural source sections."
    candidates_text = "\n".join(
        f"- [{candidate['type']}] {candidate['name']}: {candidate['one_liner']}"
        for candidate in candidates
    )
    page_provenance = ""
    if compact_pages:
        page_provenance = (
            "\n\n## Source Page Provenance\n\n"
            + "\n".join(
                f"- p. {p['page']}: {p['words']} words, hash `{p['hash']}`"
                for p in compact_pages
            )
            + "\n"
        )

    source_sections = []
    for idx, section in enumerate(sections, 1):
        level = max(2, min(int(section.get("level") or 2), 6))
        source_sections.append(
            "\n".join(
                [
                    f"<!-- section:{section.get('id') or _section_id(idx)} page:{int(section.get('page') or 1)} -->",
                    f"{'#' * level} {section.get('title') or f'Section {idx}'}",
                    "",
                    str(section.get("text") or "").strip(),
                ]
            ).strip()
        )

    fm = yaml.safe_dump(
        frontmatter,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    ).strip()
    source_sections_text = "\n\n".join(source_sections)
    figures_section = ""
    if saved_images:
        figures_section = "\n\n## Embedded Figures\n\n" + "\n\n".join(
            f"![[{img['obsidian_path']}]]\n*Figure (p.{img['page']})*"
            for img in saved_images
        )
    return (
        f"---\n{fm}\n---\n\n"
        "## Summary\n\n"
        f"Instant structural L1 for **{parsed.title}**. The full source text is preserved "
        "below with stable section markers; L2/L3 extraction runs asynchronously.\n\n"
        "## 1. Key Claims\n\n"
        f"{key_claims_text}\n"
        f"{page_provenance}"
        "\n## 2. Atom Candidates\n\n"
        f"{candidates_text}\n\n"
        "## Source Sections\n\n"
        f"{source_sections_text}"
        f"{figures_section}\n"
    )


def generate_l1_structural_context(
    paths: cfg.WikiPaths,
    source_id: int,
    relpath: str,
    content_hash: str,
    *,
    existing_context_id: str | None = None,
) -> str | None:
    """Create an L1 Context from parser structure only."""
    file_path = paths.root / relpath
    if not file_path.exists():
        print(f"  [Error] File does not exist at: {file_path}")
        return None

    try:
        resolved_source = _resolve_reference_source(paths, file_path)
        parsed = parsers.parse(resolved_source)
    except Exception as e:
        print(f"  [Error] Parsing file failed for {relpath}: {e}")
        db.set_source_layer_status(paths.state_db, source_id, "l1", "error", error=str(e))
        return None

    context_id = existing_context_id or _generate_id(consts.PREFIX_L1)
    saved_images = _save_pdf_images(parsed, relpath, paths)
    page_content = _build_structural_context_page(
        context_id=context_id,
        parsed=parsed,
        relpath=relpath,
        content_hash=content_hash,
        today=_now_iso(),
        saved_images=saved_images or None,
    )

    paths.contexts.mkdir(parents=True, exist_ok=True)
    context_path = paths.contexts / f"{context_id}.md"
    operation = "updated" if context_path.exists() else "created"
    context_path.write_text(page_content, encoding="utf-8")

    with db.connect(paths.state_db) as conn:
        conn.execute(
            "UPDATE sources SET context_id = ? WHERE id = ?",
            (context_id, source_id),
        )
        conn.execute(
            "UPDATE sources SET l1_status = 'done', layer_error = NULL WHERE id = ?",
            (source_id,),
        )

    _record_pdf_pages_for_parsed(paths, source_id, relpath, parsed)
    db.record_source_page(
        paths.state_db,
        source_id,
        f"{consts.LAYER_L1}/{context_id}.md",
        operation,
    )
    return context_id


def _build_vision_client(_config: dict, main_client):
    """Return a vision-capable client for image inference.

    Resolution order:
    1. main_client supports vision → reuse main_client
    2. ollama configured and primary=ollama → reuse main_client if vision-capable
    3. None (image inference disabled)
    """
    if getattr(main_client, "supports_vision", False):
        return main_client
    return None


def register_and_generate_l1(
    paths: cfg.WikiPaths,
    source_id: int,
    relpath: str,
    content_hash: str,
    *,
    existing_context_id: str | None = None,
) -> str | None:
    """Wrapper that explicitly prevents passing an LLM client.
    Runs the fast structural L1 path only.
    """
    return generate_l1_structural_context(
        paths,
        source_id,
        relpath,
        content_hash,
        existing_context_id=existing_context_id,
    )


def generate_l1_summary(
    paths: cfg.WikiPaths,
    source_id: int,
    relpath: str,
    content_hash: str,
    client,  # LLM client (OllamaClient or AntigravityCliClient)
    *,
    config: dict | None = None,
    existing_context_id: str | None = None,
    ) -> str | None:
    """Generate an L1 Context page for a source file.

    Returns the CTX-UUID if successful, None on failure.
    The page is written to `.curator/Collections/01_Contexts/<CTX-UUID>.md`.
    """
    from . import prompts

    if (config or {}).get("llm", {}).get("instant_l1", True):
        return register_and_generate_l1(
            paths,
            source_id,
            relpath,
            content_hash,
            existing_context_id=existing_context_id,
        )

    file_path = paths.root / relpath
    if not file_path.exists():
        print(f"  [Error] File does not exist at: {file_path}")
        return None

    try:
        parsed = parsers.parse(file_path)
    except Exception as e:
        print(f"  [Error] Parsing file failed for {relpath}: {e}")
        db.set_source_layer_status(paths.state_db, source_id, "l1", "error", error=str(e))
        return None

    vision_client = _build_vision_client(config or {}, client)
    has_vision = vision_client is not None

    # --- Vision: describe standalone image files ---
    if parsed.file_type == "image":
        if has_vision:
            try:
                img_data = file_path.read_bytes()
                descs = _describe_images_with_vision(vision_client, [img_data], context=parsed.title)
                source_text = f"[Image: {file_path.name}]\n\n" + (descs[0] if descs else "")
            except Exception as e:
                print(f"  [Warn] Could not describe image {relpath}: {e}")
                source_text = f"[Image: {file_path.name}] — vision inference unavailable"
        else:
            print(
                f"  [Info] Skipping image inference for {relpath}: "
                f"model '{getattr(client, 'model', '?')}' does not support vision. "
                f"Configure a vision model via llm.vision_model in config.yml "
                f"(e.g. gemma4:31b-it, gemma3:12b, llava:latest, qwen2.5-vl:7b)."
            )
            source_text = f"[Image: {file_path.name}] — no vision model configured"
    else:
        source_text = parsed.text

        # --- Vision: describe images linked from markdown documents ---
        if parsed.linked_images and has_vision:
            img_bytes: list[bytes] = []
            img_names: list[str] = []
            for raw_link in parsed.linked_images[:MAX_IMAGES_PER_DOC]:
                img_path = _resolve_image_link(raw_link, file_path, paths.root)
                if img_path:
                    try:
                        img_bytes.append(img_path.read_bytes())
                        img_names.append(img_path.name)
                    except OSError:
                        pass
            if img_bytes:
                print(f"  [Info] Describing {len(img_bytes)} linked image(s) via vision…")
                descs = _describe_images_with_vision(vision_client, img_bytes, context=parsed.title)
                if descs:
                    img_section = "\n\n".join(
                        f"**[Image: {name}]**\n{desc}"
                        for name, desc in zip(img_names, descs)
                    )
                    source_text = source_text + "\n\n## Embedded Images\n\n" + img_section

        # --- Vision: describe images embedded in PDFs ---
        pdf_images = parsed.metadata.get("pdf_images", [])
        if pdf_images and has_vision:
            pdf_img_bytes = [img["data"] for img in pdf_images[:MAX_IMAGES_PER_DOC]]
            if pdf_img_bytes:
                print(f"  [Info] Describing {len(pdf_img_bytes)} PDF image(s) via vision…")
                descs = _describe_images_with_vision(
                    vision_client, pdf_img_bytes, context=parsed.title
                )
                if descs:
                    pdf_section = "\n\n".join(
                        f"**[PDF Image, Page {pdf_images[i]['page']}]**\n{desc}"
                        for i, desc in enumerate(descs)
                    )
                    source_text = source_text + "\n\n## PDF Figures\n\n" + pdf_section

    chunk_size = getattr(client, "optimal_chunk_chars", 30000)
    
    if len(source_text) <= chunk_size + 5000:
        chunks = [source_text]
    else:
        overlap = min(2500, int(chunk_size * 0.1))
        chunks = _chunk_text(source_text, chunk_size=chunk_size, overlap=overlap)

    all_summaries = []
    all_key_claims = []
    all_atom_candidates = []
    all_tags = []
    domain = None

    if len(chunks) > 1:
        print(f"  [Info] Text is long ({len(source_text)} chars). Processing in {len(chunks)} chunk(s).")

    for idx, chunk in enumerate(chunks, 1):
        if len(chunks) > 1:
            print(f"    -> Summarizing chunk {idx}/{len(chunks)}...")
        chunk_data, chunk_error = _summarize_chunk_with_fallback(
            client,
            prompts,
            title=parsed.title,
            chunk=chunk,
            label=f"chunk {idx}",
        )
        if chunk_error:
            print(f"  [Error] Failed to summarize chunk {idx}: {chunk_error}")
            db.set_source_layer_status(
                paths.state_db, source_id, "l1", "error", error=str(chunk_error)
            )
            return None

        for data in chunk_data:
            summary_val = data.get("summary")
            if summary_val:
                if isinstance(summary_val, str):
                    # Some local LLMs emit \\n in JSON strings instead of the proper
                    # \n JSON escape. After json.loads those become literal 2-char \n
                    # sequences. Normalize them to real newlines before writing.
                    summary_val = summary_val.replace("\\n", "\n").replace("\\t", "\t")
                    all_summaries.append(summary_val)
                else:
                    all_summaries.append(json.dumps(summary_val, indent=2, ensure_ascii=False))
            all_key_claims.extend(data.get("key_claims", []))
            all_atom_candidates.extend(data.get("atom_candidates", []))
            all_tags.extend(data.get("tags", []))
            if not domain and data.get("domain"):
                domain = data["domain"]

    # Deduplicate claims and candidates
    seen_claims = set()
    unique_key_claims = []
    for claim in all_key_claims:
        clean = claim.strip()
        if clean and clean not in seen_claims:
            seen_claims.add(clean)
            unique_key_claims.append(clean)

    unique_atom_candidates = _prepare_atom_candidates(all_atom_candidates)

    unique_tags = list(set(tag.strip() for tag in all_tags if tag.strip()))

    combined_summary = "\n\n".join(all_summaries) if all_summaries else ""

    context_id = existing_context_id or _generate_id(consts.PREFIX_L1)
    today = _now_iso()

    candidates_text = "\n".join(
        f"- [{c.get('type', 'fact')}] {c.get('name', '')}: {c.get('one_liner', '')}"
        for c in unique_atom_candidates
    )
    key_claims_text = "\n".join(f"- {c}" for c in unique_key_claims)
    pdf_pages = parsed.metadata.get("pdf_pages") or []
    source_pages_fm = ""
    source_pages_body = ""
    if parsed.file_type == "pdf" and isinstance(pdf_pages, list):
        compact_pages = [
            {
                "page": int(p.get("page") or 0),
                "hash": str(p.get("content_hash") or "")[:16],
                "chars": int(p.get("char_count") or 0),
                "words": int(p.get("word_count") or 0),
            }
            for p in pdf_pages
            if int(p.get("page") or 0) > 0
        ]
        source_pages_fm = (
            f"source_page_count: {len(compact_pages)}\n"
            f"source_pages: {json.dumps(compact_pages, ensure_ascii=False)}\n"
        )
        if compact_pages:
            source_pages_body = (
                "\n\n## Source Page Provenance\n\n"
                + "\n".join(
                    f"- p. {p['page']}: {p['words']} words, hash `{p['hash']}`"
                    for p in compact_pages
                )
                + "\n"
            )

    saved_images = _save_pdf_images(parsed, relpath, paths)
    embedded_images_fm = ""
    figures_body = ""
    if saved_images:
        embedded_images_fm = (
            f"embedded_images: {json.dumps([{'obsidian_path': i['obsidian_path'], 'page': i['page']} for i in saved_images], ensure_ascii=False)}\n"
        )
        figures_body = "\n\n## Embedded Figures\n\n" + "\n\n".join(
            f"![[{img['obsidian_path']}]]\n*Figure (p.{img['page']})*"
            for img in saved_images
        )

    page_content = (
        f"---\n"
        f"id: {context_id}\n"
        f"type: context\n"
        f"source_path: \"[[{relpath.removesuffix('.md')}]]\"\n"
        f"source_hash: {content_hash}\n"
        f"{source_pages_fm}"
        f"{embedded_images_fm}"
        f"domain: \"{domain or 'general'}\"\n"
        f"last_updated: {today}\n"
        f"tags: {json.dumps(unique_tags)}\n"
        f"---\n\n"
        f"## Summary\n\n"
        f"{combined_summary}\n\n"
        f"## 1. Key Claims\n\n"
        f"{key_claims_text}\n\n"
        f"{source_pages_body}"
        f"## 2. Atom Candidates\n\n"
        f"{candidates_text}"
        f"{figures_body}\n"
    )

    # Write the L1 context page
    paths.contexts.mkdir(parents=True, exist_ok=True)
    context_path = paths.contexts / f"{context_id}.md"
    operation = "updated" if context_path.exists() else "created"
    context_path.write_text(page_content, encoding="utf-8")

    # Record context_id in DB
    with db.connect(paths.state_db) as conn:
        conn.execute(
            "UPDATE sources SET context_id = ? WHERE id = ?",
            (context_id, source_id),
        )
        conn.execute(
            "UPDATE sources SET l1_status = 'done', layer_error = NULL WHERE id = ?",
            (source_id,),
        )

    _record_pdf_pages_for_parsed(paths, source_id, relpath, parsed)
    db.record_source_page(
        paths.state_db,
        source_id,
        f"{consts.LAYER_L1}/{context_id}.md",
        operation,
    )

    return context_id


# ---------------------------------------------------------------------------
# Core file registration
# ---------------------------------------------------------------------------


def add_file(
    paths: cfg.WikiPaths,
    source: Path,
) -> AddOutcome:
    """Add a single file to the tracking DB. Does not generate L1 summary.

    L1 summary generation requires an LLM client — call `generate_l1_summary()`
    separately after this returns `AddResult.ADDED`.
    """
    source = source.expanduser().resolve()

    # Guard: file must exist
    if not source.exists() or not source.is_file():
        return AddOutcome(
            result=AddResult.ERROR,
            source_path=source,
            relpath=str(source),
            message=f"File not found: {source}",
        )

    # Guard: file type must be supported
    if not parsers.is_supported(source):
        return AddOutcome(
            result=AddResult.SKIPPED_UNSUPPORTED,
            source_path=source,
            relpath=str(source),
            message=f"Unsupported file type: {source.suffix or '(no extension)'}",
        )

    # Guard: must be inside one of raw_dirs but NOT in collections
    in_raw = _is_inside_raw(source, paths.raw_dirs)
    try:
        source.relative_to(paths.collections.resolve())
        in_raw = False
    except ValueError:
        pass

    if not in_raw:
        return AddOutcome(
            result=AddResult.SKIPPED_UNSUPPORTED,
            source_path=source,
            relpath=str(source),
            message=(
                f"File is outside allowed raw directories or inside "
                f".curator/Collections: {source}"
            ),
        )

    # Parse
    try:
        resolved_source = _resolve_reference_source(paths, source)
        parsed = parsers.parse(resolved_source)
    except parsers.ParserError as e:
        return AddOutcome(
            result=AddResult.ERROR,
            source_path=source,
            relpath=str(source),
            message=f"Parse failed: {e}",
        )

    try:
        relpath = str(source.relative_to(paths.root.resolve()))
    except ValueError:
        relpath = str(source)

    with db.connect(paths.state_db) as conn:
        existing = conn.execute(
            "SELECT id, relpath, content_hash, context_id FROM sources WHERE relpath = ?",
            (relpath,),
        ).fetchone()

        if existing is not None:
            if existing["content_hash"] == parsed.content_hash:
                _record_pdf_pages_conn(conn, existing["id"], relpath, parsed)
                return AddOutcome(
                    result=AddResult.DEDUPED,
                    source_path=source,
                    relpath=relpath,
                    title=parsed.title,
                    file_type=parsed.file_type,
                    bytes=parsed.bytes,
                    word_count=parsed.word_count,
                    content_hash=parsed.content_hash,
                    source_id=existing["id"],
                    context_id=existing["context_id"],
                    message=f"Already tracked and unmodified: #{existing['id']}",
                )
            else:
                # Content changed — reset to pending, clear L1 Context ID
                conn.execute(
                    "UPDATE sources SET content_hash = ?, bytes = ?, status = 'pending', "
                    "last_ingested = NULL, context_id = NULL, "
                    "l1_status = 'pending', l2_status = 'pending', "
                    "l3_status = 'pending', l4_status = 'pending', layer_error = NULL "
                    "WHERE id = ?",
                    (parsed.content_hash, parsed.bytes, existing["id"]),
                )
                _record_pdf_pages_conn(conn, existing["id"], relpath, parsed)
                return AddOutcome(
                    result=AddResult.ADDED,
                    source_path=source,
                    relpath=relpath,
                    title=parsed.title,
                    file_type=parsed.file_type,
                    bytes=parsed.bytes,
                    word_count=parsed.word_count,
                    content_hash=parsed.content_hash,
                    source_id=existing["id"],
                    message=f"Updated #{existing['id']} (content changed)",
                )

        # Near-empty check (likely scanned PDF)
        if parsed.is_empty:
            status = "error"
            message = (
                f"Extracted only {parsed.word_count} words — likely a scanned "
                f"PDF or empty file. OCR not yet supported."
            )
            result_kind = AddResult.SKIPPED_EMPTY
        else:
            status = "pending"
            message = f"Added as #?: {parsed.title}"
            result_kind = AddResult.ADDED

        error_reason = "empty_file" if parsed.is_empty else None
        cur = conn.execute(
            """
            INSERT INTO sources (relpath, content_hash, file_type, bytes, added_at, status, error_reason)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                relpath,
                parsed.content_hash,
                parsed.file_type,
                parsed.bytes,
                _now_iso(),
                status,
                error_reason,
            ),
        )
        source_id = cur.lastrowid
        _record_pdf_pages_conn(conn, source_id, relpath, parsed)
        if parsed.is_empty:
            conn.execute(
                "UPDATE sources SET l1_status = 'error', layer_error = ? WHERE id = ?",
                (error_reason, source_id),
            )
        message = message.replace("#?", f"#{source_id}")

    return AddOutcome(
        result=result_kind,
        source_path=source,
        relpath=relpath,
        title=parsed.title,
        file_type=parsed.file_type,
        bytes=parsed.bytes,
        word_count=parsed.word_count,
        content_hash=parsed.content_hash,
        source_id=source_id,
        message=message,
    )


def import_source_file(
    paths: cfg.WikiPaths,
    source: Path,
    *,
    policy: str = "mirror_03_to_04",
    destination: str | Path | None = None,
    dry_run: bool = False,
    logical_source_id: str = "",
) -> AddOutcome:
    """Safely copy an arbitrary file into the vault, then register it.

    The default policy mirrors files from 03_Notes into 04_Resources and puts
    external files under 04_Resources/Imports. Files already in allowed raw
    directories are registered in place unless the mirror policy remaps them.
    """
    if policy in {"reference", "ref"}:
        source = source.expanduser().resolve()
        if not source.exists() or not source.is_file():
            return AddOutcome(
                result=AddResult.ERROR,
                source_path=source,
                relpath=str(source),
                message=f"File not found: {source}",
            )
        if not parsers.is_supported(source):
            return AddOutcome(
                result=AddResult.SKIPPED_UNSUPPORTED,
                source_path=source,
                relpath=str(source),
                message=f"Unsupported file type: {source.suffix or '(no extension)'}",
            )
        try:
            parsed = parsers.parse(source)
        except parsers.ParserError as exc:
            return AddOutcome(
                result=AddResult.ERROR,
                source_path=source,
                relpath=str(source),
                message=f"Parse failed: {exc}",
            )

        relpath = str(source)
        logical_id = logical_source_id or _default_logical_source_id(source)
        if dry_run:
            return AddOutcome(
                result=AddResult.DEDUPED,
                source_path=source,
                relpath=relpath,
                title=parsed.title,
                file_type=parsed.file_type,
                bytes=parsed.bytes,
                word_count=parsed.word_count,
                content_hash=parsed.content_hash,
                message=(
                    "Dry run: would register external reference "
                    f"{source} as {logical_id}"
                ),
            )

        result_kind = AddResult.ADDED
        status = "pending"
        error_reason = None
        message = f"Added external reference as #?: {parsed.title}"
        if parsed.is_empty:
            status = "error"
            error_reason = "empty_file"
            result_kind = AddResult.SKIPPED_EMPTY
            message = (
                f"Extracted only {parsed.word_count} words — likely a scanned "
                f"PDF or empty file. OCR not yet supported."
            )

        with db.connect(paths.state_db) as conn:
            existing = conn.execute(
                "SELECT id, relpath, content_hash, context_id FROM sources "
                "WHERE relpath = ? OR logical_source_id = ?",
                (relpath, logical_id),
            ).fetchone()
            if existing is not None:
                if existing["content_hash"] == parsed.content_hash:
                    conn.execute(
                        """
                        UPDATE sources
                        SET external_path = ?, is_reference = 1,
                            logical_source_id = ?, import_origin = ?,
                            import_policy = ?
                        WHERE id = ?
                        """,
                        (str(source), logical_id, str(source), "reference", existing["id"]),
                    )
                    _record_pdf_pages_conn(conn, existing["id"], relpath, parsed)
                    return AddOutcome(
                        result=AddResult.DEDUPED,
                        source_path=source,
                        relpath=relpath,
                        title=parsed.title,
                        file_type=parsed.file_type,
                        bytes=parsed.bytes,
                        word_count=parsed.word_count,
                        content_hash=parsed.content_hash,
                        source_id=existing["id"],
                        context_id=existing["context_id"],
                        message=f"Already tracked external reference: #{existing['id']}",
                    )
                conn.execute(
                    """
                    UPDATE sources
                    SET relpath = ?, content_hash = ?, file_type = ?, bytes = ?,
                        status = ?, last_ingested = NULL, context_id = NULL,
                        l1_status = 'pending', l2_status = 'pending',
                        l3_status = 'pending', l4_status = 'pending',
                        layer_error = NULL, error_reason = ?,
                        external_path = ?, is_reference = 1,
                        logical_source_id = ?, import_origin = ?,
                        import_policy = ?
                    WHERE id = ?
                    """,
                    (
                        relpath,
                        parsed.content_hash,
                        parsed.file_type,
                        parsed.bytes,
                        status,
                        error_reason,
                        str(source),
                        logical_id,
                        str(source),
                        "reference",
                        existing["id"],
                    ),
                )
                source_id = int(existing["id"])
                result_kind = AddResult.ADDED
                message = f"Updated external reference #{source_id} (content changed)"
            else:
                cur = conn.execute(
                    """
                    INSERT INTO sources
                        (relpath, content_hash, file_type, bytes, added_at,
                         status, error_reason, external_path, is_reference,
                         logical_source_id, import_origin, import_policy)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?)
                    """,
                    (
                        relpath,
                        parsed.content_hash,
                        parsed.file_type,
                        parsed.bytes,
                        _now_iso(),
                        status,
                        error_reason,
                        str(source),
                        logical_id,
                        str(source),
                        "reference",
                    ),
                )
                source_id = int(cur.lastrowid)

            _record_pdf_pages_conn(conn, source_id, relpath, parsed)
            if parsed.is_empty:
                conn.execute(
                    "UPDATE sources SET l1_status = 'error', layer_error = ? WHERE id = ?",
                    (error_reason, source_id),
                )
            message = message.replace("#?", f"#{source_id}")

        return AddOutcome(
            result=result_kind,
            source_path=source,
            relpath=relpath,
            title=parsed.title,
            file_type=parsed.file_type,
            bytes=parsed.bytes,
            word_count=parsed.word_count,
            content_hash=parsed.content_hash,
            source_id=source_id,
            message=message,
        )

    try:
        plan = safe_import_destination(
            paths,
            source,
            policy=policy,
            destination=destination,
        )
    except Exception as exc:
        return AddOutcome(
            result=AddResult.ERROR,
            source_path=source,
            relpath=str(source),
            message=str(exc),
        )

    if dry_run:
        return AddOutcome(
            result=AddResult.DEDUPED,
            source_path=plan.source_path,
            relpath=plan.relpath,
            message=(
                "Dry run: would "
                + ("copy" if plan.copied else "register")
                + f" {plan.source_path} -> {plan.destination_path}"
            ),
        )

    if plan.copied:
        plan.destination_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(plan.source_path, plan.destination_path)

    outcome = add_file(paths, plan.destination_path)
    if outcome.source_id is not None:
        with db.connect(paths.state_db) as conn:
            conn.execute(
                """
                UPDATE sources
                SET import_origin = ?, import_policy = ?, is_reference = 0
                WHERE id = ?
                """,
                (str(plan.source_path), plan.policy, outcome.source_id),
            )

    if plan.copied and outcome.result != AddResult.ERROR:
        outcome.message = f"{outcome.message} (imported from {plan.source_path})"
    return outcome


def iter_addable_files(root: Path, recursive: bool) -> Iterable[Path]:
    """Yield every supported file at or under `root`."""
    root = root.expanduser().resolve()
    if not root.exists():
        return
    if root.is_file():
        if parsers.is_supported(root):
            yield root
        return
    if root.is_dir():
        iterator = root.rglob("*") if recursive else root.iterdir()
        for child in iterator:
            if child.is_file() and not child.name.startswith(".") and parsers.is_supported(child):
                yield child


# ---------------------------------------------------------------------------
# DB query helpers
# ---------------------------------------------------------------------------


def list_sources(
    paths: cfg.WikiPaths, status_filter: str | None = None
) -> list[dict]:
    """Return all tracked sources as a list of dicts, ordered by id."""
    query = "SELECT * FROM sources"
    params: tuple = ()
    if status_filter:
        query += " WHERE status = ?"
        params = (status_filter,)
    query += " ORDER BY id ASC"

    with db.connect(paths.state_db) as conn:
        rows = conn.execute(query, params).fetchall()
        return [dict(row) for row in rows]


def get_source(paths: cfg.WikiPaths, source_id: int) -> dict | None:
    """Fetch a single source row by id."""
    with db.connect(paths.state_db) as conn:
        row = conn.execute(
            "SELECT * FROM sources WHERE id = ?", (source_id,)
        ).fetchone()
        return dict(row) if row else None


def mark_source_pending(
    paths: cfg.WikiPaths, source_id: int
) -> tuple[bool, str]:
    """Reset a source's status to 'pending' so it can be re-ingested."""
    row = get_source(paths, source_id)
    if row is None:
        return False, f"No source with id {source_id}"

    file_path = paths.root / row["relpath"]
    if not file_path.exists():
        return False, f"Source file no longer on disk: {row['relpath']}"

    with db.connect(paths.state_db) as conn:
        conn.execute(
            "UPDATE sources SET status = 'pending', last_ingested = NULL, "
            "context_id = NULL, l1_status = 'pending', l2_status = 'pending', "
            "l3_status = 'pending', l4_status = 'pending', layer_error = NULL WHERE id = ?",
            (source_id,),
        )
        conn.commit()

    return True, f"Marked #{source_id} ({row['relpath']}) as pending"


def remove_source(
    paths: cfg.WikiPaths, source_id: int, delete_file: bool = True
) -> tuple[bool, str]:
    """Remove a source from tracking."""
    row = get_source(paths, source_id)
    if row is None:
        return False, f"No source with id {source_id}"

    file_path = paths.root / row["relpath"]

    with db.connect(paths.state_db) as conn:
        conn.execute("DELETE FROM source_pages WHERE source_id = ?", (source_id,))
        conn.execute("DELETE FROM ingest_runs WHERE source_id = ?", (source_id,))
        conn.execute("DELETE FROM sources WHERE id = ?", (source_id,))

    deleted_file = False
    if delete_file and file_path.exists() and _is_inside_raw(file_path, paths.raw_dirs):
        try:
            file_path.unlink()
            deleted_file = True
        except OSError as e:
            return True, f"Removed #{source_id} from DB but failed to delete file: {e}"

    msg = f"Removed #{source_id} ({row['relpath']})"
    if deleted_file:
        msg += " — file deleted from raw dirs"
    elif delete_file:
        msg += " — file was outside raw dirs, left in place"
    return True, msg
