"""Vault schema migration helpers.

Bump VAULT_SCHEMA_VERSION in constants.py and add a step to _MIGRATION_STEPS
whenever Collections/*.md or .curator/config.yml structure changes in a way
that requires existing vaults to be updated.

Usage:
    wiki migrate          # detect and apply all pending steps
    wiki migrate --check  # report what would be done, no writes
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

import yaml

from . import config as cfg
from . import constants as consts

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Minimum required frontmatter fields per layer — used by the stale-file scan.
# A file missing any of these was generated by an old/broken pipeline run and
# its source should be re-queued for regeneration.
# ---------------------------------------------------------------------------

_REQUIRED_FIELDS: dict[str, frozenset[str]] = {
    consts.LAYER_L1: frozenset({"id", "type", "source_path"}),
    consts.LAYER_L2: frozenset({"id", "type", "unit_type"}),
    consts.LAYER_L3: frozenset({"id", "type"}),
    consts.LAYER_L4: frozenset({"id", "type"}),
}


# ---------------------------------------------------------------------------
# Result types
# ---------------------------------------------------------------------------

@dataclass
class StaleFile:
    path: Path
    layer: str
    missing_fields: frozenset[str]


@dataclass
class MigrationResult:
    current_version: int
    target_version: int
    steps_run: list[str] = field(default_factory=list)
    steps_skipped: list[str] = field(default_factory=list)
    errors: dict[str, str] = field(default_factory=dict)
    stale_files: list[StaleFile] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors

    @property
    def already_current(self) -> bool:
        return self.current_version >= self.target_version


# ---------------------------------------------------------------------------
# Schema version helpers
# ---------------------------------------------------------------------------

def get_vault_schema_version(paths: cfg.WikiPaths) -> int:
    """Read vault_schema_version directly from vault config file (not merged config).

    Returns 0 when the key is absent — indicating a pre-migration vault.
    """
    if not paths.config_file.exists():
        return 0
    try:
        data = yaml.safe_load(paths.config_file.read_text(encoding="utf-8")) or {}
        return int(data.get("vault_schema_version") or 0)
    except Exception:
        return 0


def set_vault_schema_version(paths: cfg.WikiPaths, version: int) -> None:
    """Write vault_schema_version into vault config file."""
    if not paths.config_file.exists():
        paths.internal.mkdir(parents=True, exist_ok=True)
        current: dict[str, Any] = {}
    else:
        try:
            current = yaml.safe_load(paths.config_file.read_text(encoding="utf-8")) or {}
        except Exception:
            current = {}
    current["vault_schema_version"] = version
    paths.internal.mkdir(parents=True, exist_ok=True)
    paths.config_file.write_text(
        yaml.safe_dump(current, sort_keys=False, default_flow_style=False, allow_unicode=True),
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Stale-file scan
# ---------------------------------------------------------------------------

def scan_stale_collection_files(paths: cfg.WikiPaths) -> list[StaleFile]:
    """Scan Collections/*.md for files missing required frontmatter fields.

    Returns a list of StaleFile entries. Callers decide whether to re-queue
    the affected sources or just report the issue.
    """
    stale: list[StaleFile] = []
    if not paths.collections.exists():
        return stale

    for layer_name, required in _REQUIRED_FIELDS.items():
        layer_dir = paths.collections / layer_name
        if not layer_dir.exists():
            continue
        for md_file in layer_dir.glob("*.md"):
            if md_file.name.startswith("."):
                continue
            try:
                text = md_file.read_text(encoding="utf-8", errors="ignore")
                frontmatter = _parse_frontmatter(text)
                missing = required - set(frontmatter.keys())
                if missing:
                    stale.append(StaleFile(path=md_file, layer=layer_name, missing_fields=frozenset(missing)))
            except Exception as exc:
                log.warning("Could not read %s: %s", md_file, exc)

    return stale


def _parse_frontmatter(text: str) -> dict[str, Any]:
    """Extract YAML frontmatter from a markdown file."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    try:
        return yaml.safe_load(text[3:end]) or {}
    except Exception:
        return {}


# ---------------------------------------------------------------------------
# Migration steps  (add new steps here when VAULT_SCHEMA_VERSION bumps)
# ---------------------------------------------------------------------------

def _migrate_v0_to_v1(paths: cfg.WikiPaths, _config: dict[str, Any]) -> None:
    """v0.4.1: machine-local config separation.

    load_config() and save_config() already auto-migrate this on every call.
    This explicit step just ensures the vault config is clean and the version
    is recorded — so `wiki status` stops reporting the upgrade warning.
    """
    # load_config already ran migration; re-save to flush any remaining keys
    merged = cfg.load_config(paths)
    vault_only = {
        k: v for k, v in merged.items()
        if k not in cfg.MACHINE_LOCAL_CONFIG_KEYS
    }
    cfg.save_config(paths, vault_only)


_MIGRATION_STEPS: dict[int, Callable[[cfg.WikiPaths, dict[str, Any]], None]] = {
    0: _migrate_v0_to_v1,
}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def run_migrations(
    paths: cfg.WikiPaths,
    *,
    dry_run: bool = False,
) -> MigrationResult:
    """Detect and apply all pending vault schema migrations.

    Args:
        paths:   Resolved vault paths.
        dry_run: When True, report what would be done without writing anything.

    Returns:
        MigrationResult with per-step outcomes and any stale Collection files.
    """
    target = consts.VAULT_SCHEMA_VERSION
    current = get_vault_schema_version(paths)
    config = cfg.load_config(paths)
    result = MigrationResult(current_version=current, target_version=target)

    if current >= target:
        result.stale_files = scan_stale_collection_files(paths)
        return result

    for v in range(current, target):
        step = f"v{v}→v{v+1}"
        fn = _MIGRATION_STEPS.get(v)
        if fn is None:
            result.steps_skipped.append(step)
            continue
        if dry_run:
            result.steps_run.append(step)
            continue
        try:
            fn(paths, config)
            result.steps_run.append(step)
        except Exception as exc:
            result.errors[step] = str(exc)
            log.error("Migration %s failed: %s", step, exc)
            break  # stop on first failure — don't skip ahead

    if not dry_run and result.ok:
        new_version = current + len(result.steps_run)
        set_vault_schema_version(paths, new_version)
        result.current_version = new_version

    result.stale_files = scan_stale_collection_files(paths)
    return result
