#!/usr/bin/env python3
"""Create the repo-local initialized testbed vault for llm-wiki development."""

from __future__ import annotations

import argparse
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
TESTBED_ROOT = REPO_ROOT / "testbed"
TESTBED_TEMPLATE = SRC_ROOT / "llm_wiki" / "templates" / "testbed_scenario"
WORKSPACE_NAME = "Gaussian Splatting Geometry Lab"
RAW_DIRS = ["02_Wiki", "03_Notes", "04_Resources", "06_Archives"]

if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from llm_wiki import config as cfg  # noqa: E402
from llm_wiki import db, page_writer, search  # noqa: E402
from llm_wiki.workspace_rules import prepare_workspace  # noqa: E402


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def _remove(path: Path) -> None:
    if path.is_dir():
        shutil.rmtree(path)
    elif path.exists():
        path.unlink()


def _prepare_root(root: Path, *, force: bool) -> None:
    if root.exists() and not force:
        raise SystemExit(f"{root} already exists. Use --force to reset mutable testbed state.")

    root.mkdir(parents=True, exist_ok=True)
    if force:
        for child in list(root.iterdir()):
            _remove(child)


def _ensure_testbed_source_template(root: Path) -> None:
    """Copy the exact checked-in testbed source corpus into the testbed."""
    if not TESTBED_TEMPLATE.exists():
        raise SystemExit(f"Missing testbed scenario template: {TESTBED_TEMPLATE}")
    shutil.copytree(TESTBED_TEMPLATE, root, dirs_exist_ok=True)


def _copy_template_index(paths: cfg.WikiPaths) -> None:
    template_path = SRC_ROOT / "llm_wiki" / "templates" / "index.md"
    if template_path.exists():
        shutil.copy2(template_path, paths.index)
    else:
        page_writer.rebuild_index(paths, _now_iso())


def _init_like_wiki_init(root: Path) -> cfg.WikiPaths:
    root.mkdir(parents=True, exist_ok=True)
    (root / ".obsidian").mkdir(parents=True, exist_ok=True)

    for dirname in cfg.VAULT_TOPOLOGY:
        (root / dirname).mkdir(parents=True, exist_ok=True)

    paths = cfg.WikiPaths(root=root, raw_dirs_override=RAW_DIRS)
    paths.internal.mkdir(parents=True, exist_ok=True)
    paths.collections.mkdir(parents=True, exist_ok=True)
    for layer in cfg.COLLECTION_LAYERS:
        (paths.collections / layer).mkdir(parents=True, exist_ok=True)

    config = dict(cfg.DEFAULT_CONFIG)
    config["paths"] = {
        "raw_dirs": RAW_DIRS,
        "collections_dir": cfg.DEFAULT_COLLECTIONS_DIR,
    }
    config["llm"] = dict(config.get("llm", {}))
    config["llm"]["primary"] = "gemini-cli"
    config["llm"]["fallback"] = ""
    config["llm"]["gemini_flash_model"] = "gemini-3.1-flash-lite-preview"
    cfg.save_config(paths, config)

    db.init_db(paths.state_db)
    _copy_template_index(paths)
    _write(
        paths.overview,
        """---
title: Domain Manifest
type: overview
---

# .curator/overview.md - Testbed Domain Manifest

This initialized testbed vault is generated by `scripts/create_testbed.py`.
It is used for llm-wiki development validation.
""",
    )
    _write(
        paths.ledger,
        """---
title: Ledger
type: ledger
---

# .curator/ledger.md - Testbed Override Ledger

Human-approved corrections for testbed DAG nodes are recorded here.
""",
    )
    _write(
        paths.log,
        """---
title: Curator Log
type: log
---

# .curator/log.md - Testbed Event Log
""",
    )
    search.write_qmd_config(paths, overwrite=True)
    return paths


def _write_testbed_agent_rules(root: Path) -> None:
    ws_dir = root / "01_Workspaces" / "Gaussian Splatting Geometry Lab"
    for agent in ("codex", "claude-code", "gemini-cli", "antigravity"):
        prepare_workspace(
            wiki_root=root,
            workspace=ws_dir,
            agent=agent,
            force_curate=False,
            install_rules=True,
        )


def create_testbed(*, force: bool) -> None:
    _prepare_root(TESTBED_ROOT, force=force)
    _ensure_testbed_source_template(TESTBED_ROOT)
    paths = _init_like_wiki_init(TESTBED_ROOT)
    _write_testbed_agent_rules(paths.root)
    print(f"Created initialized testbed at {TESTBED_ROOT}")



def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help="Recreate the testbed from the checked-in testbed_scenario template.",
    )
    args = parser.parse_args()
    create_testbed(force=args.force)


if __name__ == "__main__":
    main()
